// Windows installer for the Minecraft Dungeons II keyboard controller mod.
//
// One exe with the mod inside (build/payload.h, generated by build.sh). It finds
// the game through Steam's library folders (or XboxGames, for the Minecraft
// Launcher and Xbox app), copies xinput1_4.dll, default.txt
// and the offline key layout editor into Dungeons\Binaries\Win64, and can
// uninstall, switch between the Default, Recommended (author.txt) and your own
// layout, open the editor, load a layout the editor saved, or open the
// settings file. Windows loads xinput1_4.dll from the game folder first, so no
// registry change is needed (that is only for Wine; see mac/wasdmod.sh).
//
// Command line (also used by the tests under Wine):
//   /find                 print the game folder it finds
//   /status  "<folder>"   print what is installed there
//   /install "<folder>"   install without the window
//   /uninstall "<folder>" uninstall without the window (keeps saved layouts)
//   /default, /recommended, /own "<folder>"   switch the key layout
//   /off, /on "<folder>"  turn the mod off (the game starts without it) or back on
//   /recordon, /recordoff, /report "<folder>"   Record Logs, and the report file
//   /serve "<folder>"     run the key layout editor's server and print its address
typedef unsigned char BYTE;
typedef unsigned short WORD;
typedef unsigned long DWORD;
typedef long LONG;
typedef unsigned int UINT;
typedef int BOOL;
typedef void *HANDLE;
typedef long long LRESULT;
typedef unsigned long long WPARAM;
typedef long long LPARAM;
typedef unsigned long long U64;
#define IMP __declspec(dllimport)

// kernel32
IMP HANDLE CreateFileA(const char *, DWORD, DWORD, void *, DWORD, DWORD, HANDLE);
IMP BOOL ReadFile(HANDLE, void *, DWORD, DWORD *, void *);
IMP BOOL WriteFile(HANDLE, const void *, DWORD, DWORD *, void *);
IMP DWORD GetFileSize(HANDLE, DWORD *);
IMP BOOL CloseHandle(HANDLE);
IMP BOOL DeleteFileA(const char *);
IMP BOOL CopyFileA(const char *, const char *, BOOL);
IMP BOOL MoveFileExA(const char *, const char *, DWORD);
IMP DWORD GetFileAttributesA(const char *);
typedef struct { DWORD attributes; DWORD created[2], accessed[2], written[2]; DWORD sizeHigh, sizeLow; } FILEINFO;
IMP BOOL GetFileAttributesExA(const char *, int, FILEINFO *);
typedef struct { DWORD attributes; DWORD created[2], accessed[2], written[2]; DWORD sizeHigh, sizeLow, reserved0, reserved1; char name[260]; char shortName[14]; } FINDDATA;
IMP HANDLE FindFirstFileA(const char *, FINDDATA *);
IMP BOOL FindNextFileA(HANDLE, FINDDATA *);
IMP BOOL FindClose(HANDLE);
IMP BOOL SetFileTime(HANDLE, const void *, const void *, const void *);
IMP void GetSystemTimeAsFileTime(DWORD *);
IMP HANDLE GetProcessHeap(void);
IMP void *HeapAlloc(HANDLE, DWORD, U64);
IMP BOOL HeapFree(HANDLE, DWORD, void *);
IMP const char *GetCommandLineA(void);
IMP HANDLE GetStdHandle(DWORD);
IMP void ExitProcess(UINT);
IMP HANDLE GetModuleHandleA(const char *);
IMP void *GetProcAddress(HANDLE, const char *);
typedef struct { WORD year, month, weekday, day, hour, minute, second, ms; } SYSTEMTIME;
IMP void GetLocalTime(SYSTEMTIME *);
IMP DWORD GetEnvironmentVariableA(const char *, char *, DWORD);
IMP HANDLE CreateToolhelp32Snapshot(DWORD, DWORD);
typedef struct { DWORD size, usage, pid; U64 heap; DWORD module, threads, parent; LONG priority; DWORD flags; char exe[260]; } PROCESSENTRY;
IMP BOOL Process32First(HANDLE, PROCESSENTRY *);
IMP BOOL Process32Next(HANDLE, PROCESSENTRY *);
IMP HANDLE CreateThread(void *, U64, DWORD (*)(void *), void *, DWORD, DWORD *);
IMP BOOL CreateDirectoryA(const char *, void *);
IMP void Sleep(DWORD);
IMP DWORD GetLogicalDrives(void);
IMP UINT GetDriveTypeA(const char *);
// advapi32
IMP LONG RegOpenKeyExA(HANDLE, const char *, DWORD, DWORD, HANDLE *);
IMP LONG RegQueryValueExA(HANDLE, const char *, DWORD *, DWORD *, BYTE *, DWORD *);
IMP LONG RegCloseKey(HANDLE);
IMP BYTE SystemFunction036(void *, DWORD); // RtlGenRandom
// user32
typedef LRESULT (*WNDPROC)(HANDLE, UINT, WPARAM, LPARAM);
typedef struct { UINT style; WNDPROC proc; int clsExtra, wndExtra; HANDLE instance, icon, cursor, background; const char *menu, *className; } WNDCLASSA;
typedef struct { HANDLE hwnd; UINT message; WPARAM wParam; LPARAM lParam; DWORD time; LONG x, y; } MSG;
typedef struct { LONG left, top, right, bottom; } RECT;
IMP WORD RegisterClassA(const WNDCLASSA *);
IMP HANDLE CreateWindowExA(DWORD, const char *, const char *, DWORD, int, int, int, int, HANDLE, HANDLE, HANDLE, void *);
IMP LRESULT DefWindowProcA(HANDLE, UINT, WPARAM, LPARAM);
IMP BOOL GetMessageA(MSG *, HANDLE, UINT, UINT);
IMP BOOL TranslateMessage(const MSG *);
IMP LRESULT DispatchMessageA(const MSG *);
IMP BOOL IsDialogMessageA(HANDLE, MSG *);
IMP BOOL PostMessageA(HANDLE, UINT, WPARAM, LPARAM);
IMP void PostQuitMessage(int);
IMP LRESULT SendMessageA(HANDLE, UINT, WPARAM, LPARAM);
IMP BOOL SetWindowTextA(HANDLE, const char *);
IMP int MessageBoxA(HANDLE, const char *, const char *, UINT);
IMP BOOL EnableWindow(HANDLE, BOOL);
IMP BOOL ShowWindow(HANDLE, int);
IMP HANDLE LoadCursorA(HANDLE, const char *);
IMP HANDLE LoadIconA(HANDLE, const char *);
IMP HANDLE GetDC(HANDLE);
IMP int ReleaseDC(HANDLE, HANDLE);
IMP BOOL AdjustWindowRect(RECT *, DWORD, BOOL);
IMP BOOL SetProcessDPIAware(void);
// gdi32
IMP HANDLE CreateFontA(int, int, int, int, int, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, const char *);
IMP int GetDeviceCaps(HANDLE, int);
IMP int SetBkMode(HANDLE, int);
IMP HANDLE GetSysColorBrush(int);
// shell32 / comdlg32
IMP HANDLE ShellExecuteA(HANDLE, const char *, const char *, const char *, const char *, int);
IMP LONG SHGetFolderPathA(HANDLE, int, HANDLE, DWORD, char *);
typedef struct {
    DWORD size; HANDLE owner, instance; const char *filter; char *customFilter; DWORD maxCustomFilter, filterIndex;
    char *file; DWORD maxFile; char *fileTitle; DWORD maxFileTitle; const char *initialDir, *title; DWORD flags;
    WORD fileOffset, fileExtension; const char *defExt; LPARAM custData; void *hook; const char *templateName;
    void *reserved1; DWORD reserved2, flagsEx;
} OPENFILENAMEA;
IMP BOOL GetOpenFileNameA(OPENFILENAMEA *);
// ws2_32
typedef unsigned long long SOCKET;
typedef struct { WORD family, port; DWORD addr; BYTE zero[8]; } SOCKADDR_IN;
IMP int WSAStartup(WORD, void *);
IMP SOCKET socket(int, int, int);
IMP int bind(SOCKET, const void *, int);
IMP int listen(SOCKET, int);
IMP SOCKET accept(SOCKET, void *, int *);
IMP int getsockname(SOCKET, void *, int *);
IMP int setsockopt(SOCKET, int, int, const char *, int);
IMP int recv(SOCKET, char *, int, int);
IMP int send(SOCKET, const char *, int, int);
IMP int closesocket(SOCKET);

void *memset(void *p, int v, U64 n) { volatile BYTE *c = p; while (n--) *c++ = (BYTE)v; return p; }
void *memcpy(void *d, const void *s, U64 n) { volatile BYTE *o = d; const BYTE *i = s; while (n--) *o++ = *i++; return d; }
int _fltused = 0;

#include "build/payload.h" // payloadDll, payloadIni, payloadAuthor, payloadEditor

// ---------------------------------------------------------------- strings

#define PATHLEN 600
static unsigned slen(const char *s) { unsigned n = 0; while (s[n]) n++; return n; }
static void scpy(char *d, unsigned cap, const char *s) { unsigned i = 0; while (s[i] && i + 1 < cap) { d[i] = s[i]; i++; } d[i] = 0; }
static void cat(char *d, unsigned cap, const char *s) { unsigned n = slen(d); if (n < cap) scpy(d + n, cap - n, s); }
static char low(char c) { return c >= 'A' && c <= 'Z' ? c + 32 : c; }
static int sameText(const char *a, const char *b) { while (*a && low(*a) == low(*b)) a++, b++; return !*a && !*b; }
static int sameTextN(const char *a, const char *b, unsigned n) { for (unsigned i = 0; i < n; i++) if (low(a[i]) != low(b[i]) || !a[i]) return 0; return 1; }
static int contains(const char *hay, unsigned n, const char *needle) {
    unsigned m = slen(needle);
    for (unsigned i = 0; i + m <= n; i++) { unsigned j = 0; while (j < m && hay[i + j] == needle[j]) j++; if (j == m) return 1; }
    return 0;
}
static void join(char *out, const char *dir, const char *name) { scpy(out, PATHLEN, dir); cat(out, PATHLEN, "\\"); cat(out, PATHLEN, name); }

// ---------------------------------------------------------------- files

static int exists(const char *p) { return GetFileAttributesA(p) != 0xFFFFFFFF; }
static char *readAll(const char *p, DWORD *n) {
    HANDLE f = CreateFileA(p, 0x80000000 /*GENERIC_READ*/, 1 | 2 /*share read/write*/, 0, 3 /*OPEN_EXISTING*/, 0x80, 0);
    if (f == (HANDLE)-1) return 0;
    DWORD size = GetFileSize(f, 0), got = 0;
    char *b = HeapAlloc(GetProcessHeap(), 0, (U64)size + 1);
    if (b && (!ReadFile(f, b, size, &got, 0) || got != size)) { HeapFree(GetProcessHeap(), 0, b); b = 0; }
    CloseHandle(f);
    if (b) { b[size] = 0; *n = size; }
    return b;
}
static int writeAll(const char *p, const void *d, DWORD n) {
    HANDLE f = CreateFileA(p, 0x40000000 /*GENERIC_WRITE*/, 0, 0, 2 /*CREATE_ALWAYS*/, 0x80, 0);
    if (f == (HANDLE)-1) return 0;
    DWORD put = 0; BOOL ok = WriteFile(f, d, n, &put, 0) && put == n;
    CloseHandle(f);
    return ok;
}
static int sameAs(const char *p, const BYTE *d, DWORD n) {
    DWORD got; char *b = readAll(p, &got); if (!b) return 0;
    int same = got == n; for (DWORD i = 0; same && i < n; i++) if ((BYTE)b[i] != d[i]) same = 0;
    HeapFree(GetProcessHeap(), 0, b);
    return same;
}
static int isOurDll(const char *p) {
    DWORD n; char *b = readAll(p, &n); if (!b) return 0;
    int ours = contains(b, n, "Controller mod loaded") || contains(b, n, "WASD mod loaded");
    HeapFree(GetProcessHeap(), 0, b);
    return ours;
}
// Marks a file as just changed: the mod reads the newest of default.txt and the
// saved layouts, so a saved layout stays in charge after an update.
static void touch(const char *p) {
    HANDLE f = CreateFileA(p, 0x100 /*FILE_WRITE_ATTRIBUTES*/, 1 | 2, 0, 3, 0x80, 0);
    if (f == (HANDLE)-1) return;
    DWORD now[2]; GetSystemTimeAsFileTime(now); SetFileTime(f, 0, 0, now);
    CloseHandle(f);
}
static int newer(const char *a, const char *b);
static void activeSettings(const char *dir, char *out);
// Files matching `name`: finds the newest; with `each`, calls it for every one.
static int findFiles(const char *dir, const char *name, char *newest, void (*each)(const char *, const char *)) {
    char pattern[PATHLEN]; join(pattern, dir, name);
    FINDDATA f; HANDLE h = FindFirstFileA(pattern, &f);
    if (h == (HANDLE)-1) return 0;
    DWORD best[2] = {0, 0}; int found = 0;
    do {
        if (f.attributes & 0x10) continue;
        char p[PATHLEN]; join(p, dir, f.name);
        if (each) each(p, f.name);
        if (!found || f.written[1] > best[1] || (f.written[1] == best[1] && f.written[0] > best[0])) {
            best[0] = f.written[0]; best[1] = f.written[1]; found = 1;
            if (newest) scpy(newest, PATHLEN, p);
        }
    } while (FindNextFileA(h, &f));
    FindClose(h);
    return found;
}
// Saved key layouts: author.txt and the editor's wasdmod-MMDDYY.txt files.
static int findLayouts(const char *dir, char *newest, void (*each)(const char *, const char *)) {
    char a[PATHLEN], b[PATHLEN];
    int hasA = findFiles(dir, "author.txt", a, each), hasB = findFiles(dir, "wasdmod*.txt", b, each);
    if (newest && (hasA || hasB)) scpy(newest, PATHLEN, hasA && (!hasB || newer(a, b)) ? a : b);
    return hasA || hasB;
}
static const char *baseName(const char *p) { const char *b = p; for (; *p; p++) if (*p == '\\' || *p == '/') b = p + 1; return b; }
static void deleteFile(const char *p, const char *name) { (void)name; DeleteFileA(p); }
// Older versions named everything wasd-mod...: a saved layout keeps its date
// (wasd-mod-093026.txt -> wasdmod-093026.txt) and its time stamp.
static char migrateDir[PATHLEN];
static void renameLegacy(const char *p, const char *name) {
    char to[PATHLEN]; join(to, migrateDir, "wasdmod"); cat(to, PATHLEN, name + 8);
    MoveFileExA(p, to, 1 /*MOVEFILE_REPLACE_EXISTING*/);
}

static int newer(const char *a, const char *b) { // a changed after b
    FILEINFO x, y;
    if (!GetFileAttributesExA(a, 0, &x)) return 0;
    if (!GetFileAttributesExA(b, 0, &y)) return 1;
    return x.written[1] > y.written[1] || (x.written[1] == y.written[1] && x.written[0] > y.written[0]);
}

static int gameRunning(void) {
    HANDLE s = CreateToolhelp32Snapshot(2 /*TH32CS_SNAPPROCESS*/, 0);
    if (s == (HANDLE)-1) return 0;
    PROCESSENTRY e; memset(&e, 0, sizeof(e)); e.size = sizeof(e);
    int found = 0;
    for (BOOL ok = Process32First(s, &e); ok && !found; ok = Process32Next(s, &e)) if (sameText(e.exe, "Dungeons-Win64-Shipping.exe")) found = 1;
    CloseHandle(s);
    return found;
}

// ---------------------------------------------------------------- finding the game

static const char *GAME_SUB = "steamapps\\common\\Minecraft Dungeons II\\Dungeons\\Binaries\\Win64";
static int isGameDir(const char *dir) { char p[PATHLEN]; join(p, dir, "Dungeons-Win64-Shipping.exe"); return exists(p); }

static int tryLibrary(const char *lib, char *out) {
    char dir[PATHLEN]; join(dir, lib, GAME_SUB);
    if (!isGameDir(dir)) return 0;
    scpy(out, PATHLEN, dir);
    return 1;
}
static int regString(HANDLE root, const char *key, const char *value, char *out, DWORD cap) {
    HANDLE k; if (RegOpenKeyExA(root, key, 0, 0x20019 /*KEY_READ*/, &k)) return 0;
    DWORD type = 0, size = cap - 1; LONG r = RegQueryValueExA(k, value, 0, &type, (BYTE *)out, &size);
    RegCloseKey(k);
    if (r || (type != 1 && type != 2)) return 0;
    out[size < cap ? size : cap - 1] = 0;
    for (char *c = out; *c; c++) if (*c == '/') *c = '\\';
    unsigned n = slen(out); while (n && out[n - 1] == '\\') out[--n] = 0;
    return out[0] != 0;
}
// Steam's library list: every "path" "D:\\SteamLibrary" entry in libraryfolders.vdf.
static int searchLibraries(const char *steam, char *out) {
    if (tryLibrary(steam, out)) return 1;
    char p[PATHLEN]; join(p, steam, "steamapps\\libraryfolders.vdf");
    DWORD n; char *b = readAll(p, &n); if (!b) return 0;
    int found = 0;
    for (DWORD i = 0; i + 6 < n && !found; i++) {
        if (b[i] != '"' || low(b[i + 1]) != 'p' || low(b[i + 2]) != 'a' || low(b[i + 3]) != 't' || low(b[i + 4]) != 'h' || b[i + 5] != '"') continue;
        DWORD j = i + 6; while (j < n && b[j] != '"' && b[j] != '\n') j++;
        if (j >= n || b[j] != '"') continue;
        char lib[PATHLEN]; unsigned k = 0; j++;
        while (j < n && b[j] != '"' && k + 1 < sizeof(lib)) {
            if (b[j] == '\\' && j + 1 < n && b[j + 1] == '\\') j++; // "D:\\SteamLibrary"
            lib[k++] = b[j] == '/' ? '\\' : b[j];
            j++;
        }
        lib[k] = 0;
        found = tryLibrary(lib, out);
    }
    HeapFree(GetProcessHeap(), 0, b);
    return found;
}
static int findGame(char *out) {
    char steam[PATHLEN];
    if (regString((HANDLE)0x80000001 /*HKCU*/, "Software\\Valve\\Steam", "SteamPath", steam, sizeof(steam)) && searchLibraries(steam, out)) return 1;
    if (regString((HANDLE)0x80000002 /*HKLM*/, "SOFTWARE\\WOW6432Node\\Valve\\Steam", "InstallPath", steam, sizeof(steam)) && searchLibraries(steam, out)) return 1;
    if (regString((HANDLE)0x80000002, "SOFTWARE\\Valve\\Steam", "InstallPath", steam, sizeof(steam)) && searchLibraries(steam, out)) return 1;
    const char *guesses[] = {"C:\\Program Files (x86)\\Steam", "C:\\Program Files\\Steam", "D:\\SteamLibrary", "D:\\Steam", "E:\\SteamLibrary"};
    for (unsigned i = 0; i < sizeof(guesses) / sizeof(*guesses); i++) if (tryLibrary(guesses[i], out)) return 1;
    // Bought from Minecraft.net (Minecraft Launcher) or the Xbox app: X:\XboxGames on
    // any local drive (removable ones are skipped: an empty card reader asks for a disk).
    DWORD drives = GetLogicalDrives();
    for (int d = 2; d < 26; d++) {
        if (!(drives >> d & 1)) continue;
        char root[4] = {(char)('A' + d), ':', '\\', 0};
        if (GetDriveTypeA(root) != 3 /*DRIVE_FIXED*/) continue;
        char dir[PATHLEN]; scpy(dir, PATHLEN, root); cat(dir, PATHLEN, "XboxGames\\Minecraft Dungeons II\\Content\\Dungeons\\Binaries\\Win64");
        if (isGameDir(dir)) { scpy(out, PATHLEN, dir); return 1; }
    }
    return 0;
}
// A file the player picked: the game's exe in Win64, or Dungeons.exe at the top.
static int dirFromPick(const char *file, char *out) {
    scpy(out, PATHLEN, file);
    unsigned n = slen(out); while (n && out[n - 1] != '\\' && out[n - 1] != '/') n--;
    if (n) n--;
    out[n] = 0;
    if (isGameDir(out)) return 1;
    cat(out, PATHLEN, "\\Dungeons\\Binaries\\Win64");
    return isGameDir(out);
}

// ---------------------------------------------------------------- install / uninstall

// Writes a built-in layout (default.txt, author.txt), which makes it the newest
// file and so the one the mod uses; an edited copy is kept as NAME.bak.
static int putLayout(const char *dir, const char *name, const BYTE *d, DWORD n) {
    char p[PATHLEN], bak[PATHLEN]; join(p, dir, name);
    if (exists(p) && !sameAs(p, d, n)) { scpy(bak, PATHLEN, p); cat(bak, PATHLEN, ".bak"); CopyFileA(p, bak, 0); }
    return writeAll(p, d, n);
}

enum { OK, ERR_RUNNING, ERR_OTHER_DLL, ERR_WRITE };
static const char *errorText[] = {
    "",
    "Minecraft Dungeons II is running. Close it, then try again.",
    "The game folder already has a different xinput1_4.dll (another mod?).",
    "Couldn't write to the game folder. Try running this installer as administrator.",
};

static int install(const char *dir, int replaceOther) {
    if (gameRunning()) return ERR_RUNNING;
    char dll[PATHLEN], ini[PATHLEN], txt[PATHLEN], editor[PATHLEN], p[PATHLEN];
    join(dll, dir, "xinput1_4.dll"); join(ini, dir, "default.txt"); join(editor, dir, "Key Layout Editor.html");
    if (exists(dll) && !isOurDll(dll)) {
        if (!replaceOther) return ERR_OTHER_DLL;
        join(p, dir, "xinput1_4.dll.other");
        if (!CopyFileA(dll, p, 0)) return ERR_WRITE;
    }
    if (!writeAll(dll, payloadDll, sizeof(payloadDll))) return ERR_WRITE;
    join(p, dir, "xinput1_4.dll.off"); if (exists(p) && isOurDll(p)) DeleteFileA(p); // installing turns it back on
    scpy(migrateDir, PATHLEN, dir); findFiles(dir, "wasd-mod*.txt", 0, renameLegacy);
    // The settings file used to be wasd-mod.ini, then wasdmod.ini; edited ones are kept as default.txt.bak.
    const char *oldIni[] = {"wasd-mod.ini", "wasdmod.ini"};
    for (unsigned i = 0; i < 2; i++) {
        join(p, dir, oldIni[i]);
        if (exists(p)) { char bak[PATHLEN]; join(bak, dir, "default.txt.bak"); if (!sameAs(p, payloadIni, sizeof(payloadIni))) CopyFileA(p, bak, 0); DeleteFileA(p); }
    }
    join(p, dir, "wasd-mod.log"); DeleteFileA(p);
    activeSettings(dir, txt); // the layout in use before the update
    if (!putLayout(dir, "default.txt", payloadIni, sizeof(payloadIni))) return ERR_WRITE;
    writeAll(editor, payloadEditor, sizeof(payloadEditor));
    // It stays in use: a saved layout is marked newer than the fresh default.txt. (Not
    // the newest saved one: a player who picked Default stays on Default.)
    if (!sameText(baseName(txt), "default.txt") && exists(txt)) touch(txt);
    return OK;
}

static int uninstall(const char *dir, int removeLayout) {
    if (gameRunning()) return ERR_RUNNING;
    char p[PATHLEN];
    join(p, dir, "xinput1_4.dll"); if (exists(p) && isOurDll(p) && !DeleteFileA(p)) return ERR_WRITE;
    join(p, dir, "xinput1_4.dll.off"); if (exists(p) && isOurDll(p)) DeleteFileA(p);
    const char *files[] = {"default.txt", "default.txt.bak", "wasdmod.log", "wasdmod.old.log", "wasdmod-record.flag", "Key Layout Editor.html", "wasdmod.ini", "wasdmod.ini.bak", "wasd-mod.ini", "wasd-mod.ini.bak", "wasd-mod.log"};
    for (unsigned i = 0; i < sizeof(files) / sizeof(*files); i++) { join(p, dir, files[i]); DeleteFileA(p); }
    if (removeLayout) { findLayouts(dir, 0, deleteFile); findFiles(dir, "wasd-mod*.txt", 0, deleteFile); join(p, dir, "author.txt.bak"); DeleteFileA(p); }
    return OK;
}

enum { NOT_INSTALLED, INSTALLED_LATEST, INSTALLED_OLDER, OTHER_DLL, TURNED_OFF };
static int installState(const char *dir) {
    char dll[PATHLEN], off[PATHLEN]; join(dll, dir, "xinput1_4.dll"); join(off, dir, "xinput1_4.dll.off");
    if (!exists(dll)) return exists(off) && isOurDll(off) ? TURNED_OFF : NOT_INSTALLED;
    if (!isOurDll(dll)) return OTHER_DLL;
    return sameAs(dll, payloadDll, sizeof(payloadDll)) ? INSTALLED_LATEST : INSTALLED_OLDER;
}
// The settings file the mod uses: the newest saved layout when it's newer than default.txt.
static void activeSettings(const char *dir, char *out) {
    char ini[PATHLEN], txt[PATHLEN]; join(ini, dir, "default.txt");
    scpy(out, PATHLEN, findLayouts(dir, txt, 0) && newer(txt, ini) ? txt : ini);
}
// Turning the mod off renames it to xinput1_4.dll.off: the game starts without it
// and loads the system's XInput, and the settings and layouts stay for next time.
// Works with the game running too (it applies the next time the game starts).
static int turnOn(const char *dir, int on) {
    char dll[PATHLEN], off[PATHLEN]; join(dll, dir, "xinput1_4.dll"); join(off, dir, "xinput1_4.dll.off");
    if (on) return exists(dll) ? OK : isOurDll(off) && MoveFileExA(off, dll, 0) ? OK : ERR_WRITE;
    if (!exists(dll) || !isOurDll(dll)) return OK;
    return MoveFileExA(dll, off, 1 /*MOVEFILE_REPLACE_EXISTING*/) ? OK : ERR_WRITE;
}
// Switches the layout: 0 Default, 1 Recommended, 2 your newest wasdmod*.txt.
static int useLayout(const char *dir, int which) {
    char p[PATHLEN];
    if (which == 0) return putLayout(dir, "default.txt", payloadIni, sizeof(payloadIni)) ? OK : ERR_WRITE;
    if (which == 1) return putLayout(dir, "author.txt", payloadAuthor, sizeof(payloadAuthor)) ? OK : ERR_WRITE;
    if (!findFiles(dir, "wasdmod*.txt", p, 0)) return ERR_WRITE;
    touch(p);
    return OK;
}

// ---------------------------------------------------------------- window

enum { ID_PATH = 10, ID_BROWSE, ID_INSTALL, ID_UNINSTALL, ID_EDITOR, ID_LOAD, ID_SETTINGS, ID_STATUS, ID_DEFAULT, ID_RECOMMENDED, ID_OWN, ID_ONOFF, ID_RECORD };
static HANDLE onOffBtn, recordBtn;
static HANDLE mainWnd, fontNormal, fontTitle, fontSmall, statusWnd, pathWnd, installBtn, uninstallBtn, editorBtn, loadBtn, settingsBtn, layoutBtn[3];
static char ownName[PATHLEN];
static char gameDir[PATHLEN];
static int dpi = 96;
static int S(int v) { return v * dpi / 96; }
static const char *TITLE = "wasdmod";

// ---------------------------------------------------------------- key layout editor
//
// "Edit key layout" serves the editor on 127.0.0.1 (a free port, with a random
// token in every path so no other page can use it) and opens it as an app window
// (Edge or Chrome --app, otherwise the default browser). window.wasdmodHost in the
// page keeps its layouts in %APPDATA%\wasdmod\editor.json and saves straight into
// the game folder, while this window stays open.
#define WM_EDITOR_SAVED 0x8001 // WM_APP + 1
#define MAXREQ (2 << 20)
static WORD serverPort;
static char token[33], savedName[PATHLEN];

static void num10(unsigned v, char *out) { char t[12]; int n = 0; do t[n++] = (char)('0' + v % 10); while (v /= 10); int i = 0; while (n) out[i++] = t[--n]; out[i] = 0; }
static void storePath(char *out) {
    char dir[PATHLEN] = ""; out[0] = 0;
    if (!GetEnvironmentVariableA("APPDATA", dir, 300)) return;
    cat(dir, PATHLEN, "\\wasdmod"); CreateDirectoryA(dir, 0);
    join(out, dir, "editor.json");
}
static void sendAll(SOCKET s, const char *d, DWORD n) {
    while (n) { int k = send(s, d, n > 65536 ? 65536 : (int)n, 0); if (k <= 0) return; d += k; n -= (DWORD)k; }
}
static void reply(SOCKET s, const char *status, const char *type, const char *body, DWORD n) {
    char head[300] = "HTTP/1.1 ", num[12];
    cat(head, sizeof(head), status); cat(head, sizeof(head), "\r\nContent-Type: "); cat(head, sizeof(head), type);
    cat(head, sizeof(head), "\r\nCache-Control: no-store\r\nConnection: close\r\nContent-Length: ");
    num10(n, num); cat(head, sizeof(head), num); cat(head, sizeof(head), "\r\n\r\n");
    sendAll(s, head, slen(head)); sendAll(s, body, n);
}
static void replyText(SOCKET s, const char *status, const char *text) { reply(s, status, "text/plain; charset=utf-8", text, slen(text)); }

// The editor with window.wasdmodHost, after the page's first four lines (doctype,
// html, and the two meta tags build.sh puts there).
static const char *HOST_A = "<script type=\"application/json\" id=\"wasdmod-store\">";
static const char *HOST_B =
    "</script>\n<script>\n"
    "window.wasdmodHost = (() => {\n"
    "  let store = {}, chain = Promise.resolve();\n"
    "  try { store = JSON.parse(document.getElementById(\"wasdmod-store\").textContent) || {}; } catch (e) {}\n"
    "  const base = \"/";
static const char *HOST_C = "/\";\n"
    "  const send = (path, body) => fetch(base + path, { method: \"POST\", body });\n"
    "  return {\n"
    "    store,\n"
    "    set(k, v) { store[k] = v; const body = JSON.stringify(store).replace(/</g, \"\\\\u003c\"); chain = chain.then(() => send(\"store\", body)).catch(() => {}); },\n"
    "    async save(name, text) { const r = await send(\"save?name=\" + encodeURIComponent(name), text); const t = await r.text(); if (!r.ok) throw new Error(t); return t; }\n"
    "  };\n"
    "})();\n"
    "</script>\n";
static void servePage(SOCKET s) {
    char path[PATHLEN]; DWORD storeN = 0; char *saved = 0;
    storePath(path); if (path[0]) saved = readAll(path, &storeN);
    if (saved && (storeN == 0 || saved[0] != '{' || contains(saved, storeN, "</"))) { HeapFree(GetProcessHeap(), 0, saved); saved = 0; }
    DWORD off = 0, size = sizeof(payloadEditor);
    for (int lines = 0; off < size && lines < 4; off++) if (payloadEditor[off] == '\n') lines++;
    DWORD a = slen(HOST_A), b = slen(HOST_B), c = slen(HOST_C), st = saved ? storeN : 2;
    DWORD total = off + a + st + b + 32 + c + (size - off);
    char *page = HeapAlloc(GetProcessHeap(), 0, total), *o = page;
    if (!page) { replyText(s, "500 Internal Server Error", "Out of memory."); if (saved) HeapFree(GetProcessHeap(), 0, saved); return; }
    memcpy(o, payloadEditor, off); o += off;
    memcpy(o, HOST_A, a); o += a;
    memcpy(o, saved ? saved : "{}", st); o += st;
    memcpy(o, HOST_B, b); o += b;
    memcpy(o, token, 32); o += 32;
    memcpy(o, HOST_C, c); o += c;
    memcpy(o, payloadEditor + off, size - off);
    reply(s, "200 OK", "text/html; charset=utf-8", page, total);
    HeapFree(GetProcessHeap(), 0, page);
    if (saved) HeapFree(GetProcessHeap(), 0, saved);
}
static int hexVal(char c) { return c >= '0' && c <= '9' ? c - '0' : low(c) >= 'a' && low(c) <= 'f' ? low(c) - 'a' + 10 : -1; }
static void serveSave(SOCKET s, const char *query, const char *body, DWORD n) {
    char name[80]; unsigned k = 0;
    if (sameTextN(query, "name=", 5)) for (const char *q = query + 5; *q && *q != '&' && k + 1 < sizeof(name); q++) {
        if (*q == '%' && hexVal(q[1]) >= 0 && hexVal(q[2]) >= 0) { name[k++] = (char)(hexVal(q[1]) * 16 + hexVal(q[2])); q += 2; }
        else name[k++] = *q == '+' ? ' ' : *q;
    }
    name[k] = 0;
    // Only the editor's names (default.txt, author.txt, wasdmod-MMDDYY.txt); anything else is wasdmod.txt.
    int safe = 1; for (unsigned i = 0; i < k; i++) if (name[i] == '\\' || name[i] == '/' || name[i] == ':' || (BYTE)name[i] < 32) safe = 0;
    int keep = safe && ((k > 11 && sameTextN(name, "wasdmod", 7) && sameText(name + k - 4, ".txt")) || sameText(name, "author.txt") || sameText(name, "default.txt"));
    if (!keep) scpy(name, sizeof(name), "wasdmod.txt");
    if (!gameDir[0] || !isGameDir(gameDir)) return replyText(s, "409 Conflict", "The game folder wasn't found. Pick it in the setup window.");
    if (!contains(body, n, "[Buttons]") && !contains(body, n, "[Move]")) return replyText(s, "400 Bad Request", "That isn't a key layout.");
    if (!putLayout(gameDir, name, (const BYTE *)body, n)) return replyText(s, "500 Internal Server Error", errorText[ERR_WRITE]);
    scpy(savedName, sizeof(savedName), name);
    if (mainWnd) PostMessageA(mainWnd, WM_EDITOR_SAVED, 0, 0);
    int state = installState(gameDir);
    if (state == TURNED_OFF) return replyText(s, "409 Conflict", "Saved, but wasdmod is turned off: click Turn on in the setup window.");
    if (state != INSTALLED_LATEST && state != INSTALLED_OLDER) return replyText(s, "409 Conflict", "Saved, but the mod isn't installed yet: click Install in the setup window.");
    char active[PATHLEN]; activeSettings(gameDir, active);
    replyText(s, "200 OK", baseName(active));
}
static DWORD serveOne(void *arg) {
    SOCKET s = (SOCKET)arg;
    DWORD timeout = 15000; setsockopt(s, 0xFFFF /*SOL_SOCKET*/, 0x1006 /*SO_RCVTIMEO*/, (const char *)&timeout, 4);
    char *buf = HeapAlloc(GetProcessHeap(), 0, MAXREQ + 1);
    DWORD got = 0, headEnd = 0, want = 0;
    while (buf && got < MAXREQ) {
        int k = recv(s, buf + got, MAXREQ - got, 0); if (k <= 0) break;
        got += (DWORD)k;
        if (!headEnd) for (DWORD i = 0; i + 3 < got; i++) if (buf[i] == '\r' && buf[i + 1] == '\n' && buf[i + 2] == '\r' && buf[i + 3] == '\n') {
            headEnd = i + 4; want = headEnd;
            for (DWORD j = 0; j + 16 < headEnd; j++) if (sameTextN(buf + j, "\ncontent-length:", 16)) {
                DWORD v = 0; for (DWORD m = j + 16; m < headEnd && (buf[m] == ' ' || (buf[m] >= '0' && buf[m] <= '9')); m++) if (buf[m] != ' ') v = v * 10 + (DWORD)(buf[m] - '0');
                want = headEnd + (v < MAXREQ ? v : MAXREQ);
            }
            break;
        }
        if (headEnd && got >= want) break;
    }
    if (buf && headEnd) {
        buf[got] = 0;
        // "GET /<token>/ HTTP/1.1", "POST /<token>/store", "POST /<token>/save?name=..."
        int post = sameTextN(buf, "POST /", 6), get = sameTextN(buf, "GET /", 5);
        char *path = buf + (post ? 6 : 5), *rest = path + 33;
        int ours = (post || get) && headEnd > 45 && sameTextN(path, token, 32) && path[32] == '/';
        char *body = buf + headEnd; DWORD n = got - headEnd;
        if (ours && get && rest[0] == ' ') servePage(s);
        else if (ours && post && sameTextN(rest, "store ", 6)) {
            char p[PATHLEN]; storePath(p);
            if (n && body[0] == '{' && p[0] && writeAll(p, body, n)) replyText(s, "200 OK", "");
            else replyText(s, "500 Internal Server Error", "Couldn't keep the layouts.");
        } else if (ours && post && sameTextN(rest, "save?", 5)) {
            char *q = rest + 5; char *e = q; while (*e && *e != ' ') e++;
            *e = 0; serveSave(s, q, body, n);
        } else replyText(s, "404 Not Found", "Not found.");
    }
    if (buf) HeapFree(GetProcessHeap(), 0, buf);
    closesocket(s);
    return 0;
}
static DWORD acceptLoop(void *arg) {
    for (;;) {
        SOCKET s = accept((SOCKET)arg, 0, 0);
        if (s == (SOCKET)-1) { Sleep(100); continue; }
        HANDLE t = CreateThread(0, 0, serveOne, (void *)s, 0, 0); // one thread each: browsers keep idle connections open
        if (t) CloseHandle(t); else closesocket(s);
    }
}
static int startServer(void) {
    if (serverPort) return 1;
    BYTE wsa[512], r[16];
    if (WSAStartup(0x0202, wsa) || !SystemFunction036(r, 16)) return 0;
    for (int i = 0; i < 16; i++) { token[2 * i] = "0123456789abcdef"[r[i] >> 4]; token[2 * i + 1] = "0123456789abcdef"[r[i] & 15]; }
    token[32] = 0;
    SOCKET l = socket(2 /*AF_INET*/, 1 /*SOCK_STREAM*/, 6 /*TCP*/);
    if (l == (SOCKET)-1) return 0;
    SOCKADDR_IN a; memset(&a, 0, sizeof(a)); a.family = 2; a.addr = 0x0100007F; // 127.0.0.1, port 0: any free one
    int len = sizeof(a);
    if (bind(l, &a, sizeof(a)) || listen(l, 16) || getsockname(l, &a, &len)) { closesocket(l); return 0; }
    HANDLE t = CreateThread(0, 0, acceptLoop, (void *)l, 0, 0);
    if (!t) { closesocket(l); return 0; }
    CloseHandle(t);
    serverPort = (WORD)((a.port >> 8) | (a.port << 8));
    return 1;
}
static void editorUrl(char *url) {
    char num[8]; scpy(url, 120, "http://127.0.0.1:"); num10(serverPort, num);
    cat(url, 120, num); cat(url, 120, "/"); cat(url, 120, token); cat(url, 120, "/");
}
// Edge (on every Windows 10/11 PC) or Chrome, whose --app mode is a plain window.
static int findAppBrowser(char *out) {
    const char *keys[] = {"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\msedge.exe", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\chrome.exe"};
    for (unsigned i = 0; i < 2; i++) for (unsigned root = 0; root < 2; root++) {
        if (!regString((HANDLE)(U64)(root ? 0x80000001 : 0x80000002), keys[i], "", out, PATHLEN)) continue;
        if (out[0] == '"') { unsigned n = slen(out); scpy(out, PATHLEN, out + 1); if (n > 1 && out[n - 2] == '"') out[n - 2] = 0; }
        if (exists(out)) return 1;
    }
    const char *guesses[] = {"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe", "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe"};
    for (unsigned i = 0; i < 2; i++) if (exists(guesses[i])) { scpy(out, PATHLEN, guesses[i]); return 1; }
    return 0;
}
// ---------------------------------------------------------------- Record Logs
//
// While wasdmod-record.flag is in the game folder, the mod logs each key and mouse
// button it handles. Stop and save logs writes one text file to the Desktop for a
// bug report: the system, the mod's state, the layout in use and the log.
static int recordingOn(const char *dir) { char p[PATHLEN]; join(p, dir, "wasdmod-record.flag"); return exists(p); }
static int setRecording(const char *dir, int on) {
    char p[PATHLEN]; join(p, dir, "wasdmod-record.flag");
    if (!on) { DeleteFileA(p); return OK; }
    return writeAll(p, "", 0) ? OK : ERR_WRITE;
}
typedef struct { char *b; DWORD n, cap; } TEXT;
static void put(TEXT *t, const char *s, DWORD n) { while (n-- && t->n + 1 < t->cap) t->b[t->n++] = *s++; t->b[t->n] = 0; }
static void puts_(TEXT *t, const char *s) { put(t, s, slen(s)); }
static void putNum(TEXT *t, unsigned v) { char b[12]; num10(v, b); puts_(t, b); }
// The end of a file: at most `keep` bytes, starting at a line; with `settingsOnly`,
// without the comment lines (a layout's explanations).
static void putTail(TEXT *t, const char *path, DWORD keep, int settingsOnly) {
    DWORD n; char *b = readAll(path, &n); if (!b) return;
    DWORD from = n > keep ? n - keep : 0;
    if (from) while (from < n && b[from - 1] != '\n') from++;
    int skip = 0;
    for (DWORD i = from; i < n; i++) {
        if (i == from || b[i - 1] == '\n') skip = settingsOnly && (b[i] == ';' || b[i] == '\r' || b[i] == '\n');
        if (!skip && b[i] != '\r') put(t, b + i, 1);
    }
    HeapFree(GetProcessHeap(), 0, b);
}
static int writeReport(const char *dir, char *out) {
    char desk[PATHLEN] = "", p[PATHLEN], active[PATHLEN], name[64] = "wasdmod-logs-";
    if (SHGetFolderPathA(0, 0x10 /*CSIDL_DESKTOPDIRECTORY*/, 0, 0, desk) != 0 && !GetEnvironmentVariableA("USERPROFILE", desk, 300)) return ERR_WRITE;
    SYSTEMTIME t; GetLocalTime(&t);
    char d[16]; num10(t.year, d); cat(name, sizeof(name), d);
    char two[3] = {0, 0, 0};
    WORD parts[4] = {t.month, t.day, t.hour, t.minute};
    for (int i = 0; i < 4; i++) { if (i == 2) cat(name, sizeof(name), "-"); two[0] = (char)('0' + parts[i] / 10); two[1] = (char)('0' + parts[i] % 10); cat(name, sizeof(name), two); }
    cat(name, sizeof(name), ".txt");
    join(out, desk, name);
    TEXT r; r.cap = 2u << 20; r.n = 0; r.b = HeapAlloc(GetProcessHeap(), 0, r.cap); if (!r.b) return ERR_WRITE; r.b[0] = 0;
    puts_(&r, "wasdmod logs, "); putNum(&r, t.year); puts_(&r, "-"); put(&r, name + 17, 2); puts_(&r, "-"); put(&r, name + 19, 2);
    puts_(&r, " "); put(&r, name + 22, 2); puts_(&r, ":"); put(&r, name + 24, 2); puts_(&r, "\n");
    puts_(&r, "App: wasdmod setup for Windows " VERSION "\n");
    HANDLE nt = GetModuleHandleA("ntdll.dll");
    const char *(*wine)(void) = nt ? GetProcAddress(nt, "wine_get_version") : 0;
    typedef struct { DWORD size, major, minor, build, platform; WORD csd[128]; } OSVER;
    LONG (*rtlVer)(OSVER *) = nt ? GetProcAddress(nt, "RtlGetVersion") : 0;
    OSVER v; memset(&v, 0, sizeof(v)); v.size = sizeof(v);
    puts_(&r, "System: Windows ");
    if (rtlVer && !rtlVer(&v)) { putNum(&r, v.major); puts_(&r, "."); putNum(&r, v.minor); puts_(&r, "."); putNum(&r, v.build); }
    if (wine) { puts_(&r, " (Wine "); puts_(&r, wine()); puts_(&r, ")"); }
    puts_(&r, "\nGame folder: ");
    char home[PATHLEN] = ""; unsigned hl = GetEnvironmentVariableA("USERPROFILE", home, 300) ? slen(home) : 0;
    if (hl && sameTextN(dir, home, hl)) { puts_(&r, "%USERPROFILE%"); puts_(&r, dir + hl); } else puts_(&r, dir); // no user name in the report
    const char *states[] = {"not installed", "installed, up to date", "installed, older version", "a different xinput1_4.dll", "turned off"};
    puts_(&r, "\nMod: "); puts_(&r, states[installState(dir)]);
    activeSettings(dir, active);
    puts_(&r, "\nLayout in use: "); puts_(&r, exists(active) ? baseName(active) : "none"); puts_(&r, "\n");
    if (exists(active)) { puts_(&r, "\n===== "); puts_(&r, baseName(active)); puts_(&r, " =====\n"); putTail(&r, active, 64 << 10, 1); }
    join(p, dir, "wasdmod.old.log");
    if (exists(p)) { puts_(&r, "\n===== wasdmod.old.log (end) =====\n"); putTail(&r, p, 32 << 10, 0); }
    puts_(&r, "\n===== wasdmod.log =====\n");
    join(p, dir, "wasdmod.log");
    if (exists(p)) putTail(&r, p, 1200 << 10, 0); else puts_(&r, "(no log yet: start the game once with wasdmod installed)\n");
    int ok = writeAll(out, r.b, r.n);
    HeapFree(GetProcessHeap(), 0, r.b);
    return ok ? OK : ERR_WRITE;
}

static int openEditor(void) {
    char url[120], exe[PATHLEN], args[220] = "--app=";
    if (!startServer()) return 0;
    editorUrl(url);
    if (findAppBrowser(exe)) { cat(args, sizeof(args), url); cat(args, sizeof(args), " --window-size=1200,860"); ShellExecuteA(mainWnd, "open", exe, args, 0, 1); }
    else ShellExecuteA(mainWnd, "open", url, 0, 0, 1);
    return 1;
}

static void refresh(void) {
    char text[900] = "";
    int have = gameDir[0] != 0, state = have ? installState(gameDir) : NOT_INSTALLED;
    SetWindowTextA(pathWnd, have ? gameDir : "(not found)");
    unsigned end = slen(have ? gameDir : "(not found)");
    SendMessageA(pathWnd, 0xB1 /*EM_SETSEL*/, end, end); // show the end of a long path
    if (!have) scpy(text, sizeof(text), "Game not found in Steam or XboxGames. Click Browse and pick Dungeons-Win64-Shipping.exe (in Dungeons\\Binaries\\Win64) or Dungeons.exe.");
    else if (state == INSTALLED_LATEST) scpy(text, sizeof(text), "Installed and up to date. Start (or restart) the game to use it.");
    else if (state == INSTALLED_OLDER) scpy(text, sizeof(text), "An older version is installed. Click Update.");
    else if (state == OTHER_DLL) scpy(text, sizeof(text), "The game folder has a different xinput1_4.dll (another mod?). Install replaces it and keeps a copy as xinput1_4.dll.other.");
    else if (state == TURNED_OFF) scpy(text, sizeof(text), "Turned off: the game starts without wasdmod. Your layouts are kept; click Turn on to use it again.");
    else scpy(text, sizeof(text), "Not installed yet.");
    SetWindowTextA(statusWnd, text);
    SetWindowTextA(installBtn, state == INSTALLED_OLDER ? "Update" : state == INSTALLED_LATEST || state == TURNED_OFF ? "Reinstall" : "Install");
    EnableWindow(installBtn, have);
    int installed = have && (state == INSTALLED_LATEST || state == INSTALLED_OLDER || state == TURNED_OFF);
    EnableWindow(uninstallBtn, installed);
    SetWindowTextA(onOffBtn, state == TURNED_OFF ? "Turn on" : "Turn off");
    EnableWindow(onOffBtn, installed);
    SetWindowTextA(recordBtn, have && recordingOn(gameDir) ? "Stop and save logs" : "Record logs");
    EnableWindow(recordBtn, have);
    EnableWindow(editorBtn, have);
    EnableWindow(loadBtn, installed);
    EnableWindow(settingsBtn, installed);
    // The layout in use (the newest settings file) is the checked one.
    char active[PATHLEN] = "", own[PATHLEN];
    int hasOwn = have && findFiles(gameDir, "wasdmod*.txt", own, 0);
    if (installed) activeSettings(gameDir, active);
    const char *name = baseName(active);
    int current = !installed ? -1 : sameText(name, "default.txt") ? 0 : sameText(name, "author.txt") ? 1 : 2;
    scpy(ownName, sizeof(ownName), "Your own (");
    cat(ownName, sizeof(ownName), current == 2 ? name : hasOwn ? baseName(own) : "none saved yet");
    cat(ownName, sizeof(ownName), ")");
    SetWindowTextA(layoutBtn[2], ownName);
    for (int i = 0; i < 3; i++) {
        SendMessageA(layoutBtn[i], 0xF1 /*BM_SETCHECK*/, i == current, 0);
        EnableWindow(layoutBtn[i], installed && (i < 2 || hasOwn));
    }
}

static int pickFile(const char *title, const char *filter, const char *initialDir, char *out) {
    OPENFILENAMEA o; memset(&o, 0, sizeof(o));
    out[0] = 0;
    o.size = sizeof(o); o.owner = mainWnd; o.filter = filter; o.filterIndex = 1; o.file = out; o.maxFile = PATHLEN;
    o.initialDir = initialDir; o.title = title; o.flags = 0x1000 | 0x800 | 0x4 | 0x8; // must exist, hide read-only, keep directory
    return GetOpenFileNameA(&o);
}

static void onCommand(int id) {
    char p[PATHLEN];
    if (id == ID_BROWSE) {
        if (!pickFile("Find Minecraft Dungeons II", "Minecraft Dungeons II (Dungeons*.exe)\0Dungeons*.exe\0All files\0*.*\0", 0, p)) return;
        char dir[PATHLEN];
        if (dirFromPick(p, dir)) scpy(gameDir, sizeof(gameDir), dir);
        else MessageBoxA(mainWnd, "That isn't the Minecraft Dungeons II folder. Pick Dungeons-Win64-Shipping.exe (in Dungeons\\Binaries\\Win64) or Dungeons.exe.", TITLE, 0x30);
    } else if (id == ID_INSTALL) {
        int r = install(gameDir, 0);
        if (r == ERR_OTHER_DLL && MessageBoxA(mainWnd, "The game folder already has a different xinput1_4.dll (probably another mod). Replace it? A copy is kept as xinput1_4.dll.other.", TITLE, 0x4 | 0x30) == 6) r = install(gameDir, 1);
        if (r == OK) MessageBoxA(mainWnd, "Installed. Start (or restart) Minecraft Dungeons II.\n\nIn game: WASD moves, Tab opens the menu wheel (the game's own key, S, moves you now), F9 shows the key list, and the backtick key (`) turns the mod off and on.", TITLE, 0x40);
        else if (r != ERR_OTHER_DLL) MessageBoxA(mainWnd, errorText[r], TITLE, 0x30);
    } else if (id == ID_ONOFF) {
        int on = installState(gameDir) == TURNED_OFF, r = turnOn(gameDir, on);
        if (r != OK) MessageBoxA(mainWnd, "Couldn't rename xinput1_4.dll in the game folder. Close the game, or run this setup as administrator.", TITLE, 0x30);
        else MessageBoxA(mainWnd, on ? "Turned on. Start (or restart) the game to use wasdmod again."
                                     : "Turned off. From the next game start, the game runs without wasdmod; your layouts are kept.\n\n(In a running game, the backtick key (`) turns it off right away.)", TITLE, 0x40);
    } else if (id == ID_RECORD) {
        if (!recordingOn(gameDir)) {
            if (setRecording(gameDir, 1) != OK) MessageBoxA(mainWnd, errorText[ERR_WRITE], TITLE, 0x30);
            else MessageBoxA(mainWnd, "Recording logs. Play until the problem happens, then come back here and click Stop and save logs.\n\nIf the game is running, recording starts within a second; otherwise it starts with the game. Nothing you type is recorded.", TITLE, 0x40);
        } else {
            setRecording(gameDir, 0);
            if (writeReport(gameDir, p) != OK) MessageBoxA(mainWnd, "Couldn't save the logs on the Desktop.", TITLE, 0x30);
            else {
                char args[PATHLEN + 16] = "/select,\""; cat(args, sizeof(args), p); cat(args, sizeof(args), "\"");
                ShellExecuteA(mainWnd, "open", "explorer.exe", args, 0, 1);
                char msg[PATHLEN + 300] = "Saved "; cat(msg, sizeof(msg), baseName(p));
                cat(msg, sizeof(msg), " on your Desktop. It has the mod's log, your key layout and your Windows version; nothing you type is recorded.\n\nOpen GitHub to report the problem (attach the file)?");
                if (MessageBoxA(mainWnd, msg, TITLE, 0x4 | 0x40) == 6) ShellExecuteA(mainWnd, "open", "https://github.com/Wanzho/mcd2-wasd/issues/new", 0, 0, 1);
            }
        }
    } else if (id == ID_UNINSTALL) {
        int removeLayout = findLayouts(gameDir, 0, 0) && MessageBoxA(mainWnd, "Also delete your saved key layouts (author.txt, wasdmod*.txt)?", TITLE, 0x4 | 0x20) == 6;
        int r = uninstall(gameDir, removeLayout);
        MessageBoxA(mainWnd, r == OK ? "Uninstalled. The game is back to how it was." : errorText[r], TITLE, r == OK ? 0x40 : 0x30);
    } else if (id == ID_DEFAULT || id == ID_RECOMMENDED || id == ID_OWN) {
        int r = useLayout(gameDir, id - ID_DEFAULT);
        if (r != OK) MessageBoxA(mainWnd, errorText[r], TITLE, 0x30);
        refresh();
        if (r == OK) SetWindowTextA(statusWnd, "Key layout changed. Restart the game to use it.");
        return;
    } else if (id == ID_EDITOR) {
        if (openEditor()) { SetWindowTextA(statusWnd, "The key layout editor opened in its own window. Its Save to game button writes straight into the game folder while this window stays open."); return; }
        // No local server (blocked?): the editor as a file, which downloads layouts instead.
        join(p, gameDir, "Key Layout Editor.html");
        if (!sameAs(p, payloadEditor, sizeof(payloadEditor)) && !writeAll(p, payloadEditor, sizeof(payloadEditor))) { MessageBoxA(mainWnd, errorText[ERR_WRITE], TITLE, 0x30); return; }
        ShellExecuteA(mainWnd, "open", p, 0, 0, 1);
        SetWindowTextA(statusWnd, "The key layout editor opened in your browser. Pick or create a layout there and click Download file; then click \"Load layout file\" here.");
        return;
    } else if (id == ID_LOAD) {
        char downloads[PATHLEN] = "";
        if (GetEnvironmentVariableA("USERPROFILE", downloads, 300)) cat(downloads, sizeof(downloads), "\\Downloads");
        if (!pickFile("Load a key layout", "Key layout (*.ini;*.txt)\0*.ini;*.txt\0All files\0*.*\0", downloads[0] ? downloads : 0, p)) return;
        DWORD n; char *b = readAll(p, &n);
        int valid = b && (contains(b, n, "[Buttons]") || contains(b, n, "[Move]"));
        // Keep the editor's names (author.txt, default.txt, wasdmod-MMDDYY.txt); anything else becomes wasdmod.txt.
        const char *name = baseName(p); unsigned nl = slen(name);
        int keep = (nl > 11 && sameTextN(name, "wasdmod", 7) && sameText(name + nl - 4, ".txt")) || sameText(name, "author.txt") || sameText(name, "default.txt");
        char dest[PATHLEN]; join(dest, gameDir, keep ? name : "wasdmod.txt");
        if (!valid) MessageBoxA(mainWnd, "That file isn't a key layout (it has no [Buttons] or [Move] section).", TITLE, 0x30);
        else if (!writeAll(dest, b, n)) MessageBoxA(mainWnd, errorText[ERR_WRITE], TITLE, 0x30);
        else MessageBoxA(mainWnd, "Key layout loaded. Restart the game to use it.", TITLE, 0x40);
        if (b) HeapFree(GetProcessHeap(), 0, b);
    } else if (id == ID_SETTINGS) {
        activeSettings(gameDir, p);
        char quoted[PATHLEN + 2] = "\""; cat(quoted, sizeof(quoted), p); cat(quoted, sizeof(quoted), "\"");
        ShellExecuteA(mainWnd, "open", "notepad.exe", quoted, 0, 1);
        return;
    } else return;
    refresh();
}

static HANDLE control(const char *cls, const char *text, DWORD style, int x, int y, int w, int h, int id, HANDLE font) {
    HANDLE c = CreateWindowExA(cls[0] == 'E' ? 0x200 /*WS_EX_CLIENTEDGE*/ : 0, cls, text, 0x50000000 /*WS_CHILD|WS_VISIBLE*/ | style,
                               S(x), S(y), S(w), S(h), mainWnd, (HANDLE)(U64)id, GetModuleHandleA(0), 0);
    SendMessageA(c, 0x30 /*WM_SETFONT*/, (WPARAM)font, 1);
    return c;
}

static LRESULT wndProc(HANDLE w, UINT msg, WPARAM wp, LPARAM lp) {
    if (msg == 0x01) { // WM_CREATE
        mainWnd = w;
        control("STATIC", "wasdmod", 0, 20, 16, 480, 30, 0, fontTitle);
        control("STATIC", "Play Minecraft Dungeons II with WASD, mouse and keys, as a controller.", 0, 20, 48, 480, 20, 0, fontSmall);
        control("STATIC", "Game folder", 0, 20, 84, 200, 20, 0, fontNormal);
        pathWnd = control("EDIT", "", 0x80 /*ES_AUTOHSCROLL*/ | 0x800 /*ES_READONLY*/, 20, 106, 386, 26, ID_PATH, fontNormal);
        control("BUTTON", "Browse...", 0x10000 /*WS_TABSTOP*/, 414, 105, 86, 28, ID_BROWSE, fontNormal);
        statusWnd = control("STATIC", "", 0, 20, 144, 480, 42, ID_STATUS, fontNormal);
        installBtn = control("BUTTON", "Install", 0x10000 | 0x1 /*BS_DEFPUSHBUTTON*/, 20, 194, 150, 34, ID_INSTALL, fontNormal);
        uninstallBtn = control("BUTTON", "Uninstall", 0x10000, 178, 194, 110, 34, ID_UNINSTALL, fontNormal);
        onOffBtn = control("BUTTON", "Turn off", 0x10000, 296, 194, 110, 34, ID_ONOFF, fontNormal);
        control("STATIC", "Key layout", 0, 20, 246, 200, 20, 0, fontNormal);
        layoutBtn[0] = control("BUTTON", "Default (the game's own keys)", 0x10000 | 0x4 /*BS_RADIOBUTTON*/, 28, 268, 460, 22, ID_DEFAULT, fontNormal);
        layoutBtn[1] = control("BUTTON", "Recommended", 0x10000 | 0x4, 28, 292, 460, 22, ID_RECOMMENDED, fontNormal);
        layoutBtn[2] = control("BUTTON", "Your own", 0x10000 | 0x4, 28, 316, 460, 22, ID_OWN, fontNormal);
        editorBtn = control("BUTTON", "Edit key layout...", 0x10000, 20, 348, 156, 30, ID_EDITOR, fontNormal);
        loadBtn = control("BUTTON", "Load layout file...", 0x10000, 184, 348, 156, 30, ID_LOAD, fontNormal);
        settingsBtn = control("BUTTON", "Open settings file", 0x10000, 348, 348, 152, 30, ID_SETTINGS, fontNormal);
        recordBtn = control("BUTTON", "Record logs", 0x10000, 20, 392, 156, 30, ID_RECORD, fontNormal);
        control("STATIC", "Something not working? Record logs, play until it happens, then stop: a report file for GitHub.", 0, 184, 390, 316, 36, 0, fontSmall);
        control("STATIC", "Restart the game after any change. In game: Tab opens the menu wheel, F9 shows the key list, backtick (`) turns the mod off and on.", 0, 20, 436, 480, 36, 0, fontSmall);
        refresh();
        return 0;
    }
    if (msg == 0x111 /*WM_COMMAND*/ && (wp >> 16) == 0 /*BN_CLICKED*/) { onCommand((int)(wp & 0xFFFF)); return 0; }
    if (msg == 0x138 /*WM_CTLCOLORSTATIC*/ && (HANDLE)lp != pathWnd) { // labels on the window background
        SetBkMode((HANDLE)wp, 1 /*TRANSPARENT*/);
        return (LRESULT)GetSysColorBrush(15 /*COLOR_BTNFACE*/);
    }
    if (msg == WM_EDITOR_SAVED) {
        refresh();
        char text[PATHLEN + 80] = "Saved "; cat(text, sizeof(text), savedName); cat(text, sizeof(text), " from the key layout editor. Restart the game to use it.");
        SetWindowTextA(statusWnd, text);
        return 0;
    }
    if (msg == 0x02) { PostQuitMessage(0); return 0; } // WM_DESTROY
    return DefWindowProcA(w, msg, wp, lp);
}

static HANDLE createMain(void) {
    HANDLE inst = GetModuleHandleA(0);
    HANDLE dc = GetDC(0); dpi = GetDeviceCaps(dc, 88 /*LOGPIXELSX*/); ReleaseDC(0, dc);
    if (dpi < 96) dpi = 96;
    fontNormal = CreateFontA(-S(15), 0, 0, 0, 400, 0, 0, 0, 1, 0, 0, 5 /*CLEARTYPE*/, 0, "Segoe UI");
    fontSmall = CreateFontA(-S(13), 0, 0, 0, 400, 0, 0, 0, 1, 0, 0, 5, 0, "Segoe UI");
    fontTitle = CreateFontA(-S(22), 0, 0, 0, 600, 0, 0, 0, 1, 0, 0, 5, 0, "Segoe UI");
    WNDCLASSA wc; memset(&wc, 0, sizeof(wc));
    wc.proc = wndProc; wc.instance = inst; wc.className = "DungeonsControllerModSetup";
    wc.icon = LoadIconA(inst, (const char *)1); wc.cursor = LoadCursorA(0, (const char *)32512 /*IDC_ARROW*/);
    wc.background = (HANDLE)(15 + 1); // COLOR_BTNFACE
    RegisterClassA(&wc);
    DWORD style = 0x00CA0000; // caption, system menu, minimize box
    RECT r = {0, 0, S(520), S(480)}; AdjustWindowRect(&r, style, 0);
    HANDLE w = CreateWindowExA(0, wc.className, "wasdmod - Minecraft Dungeons II controller mod", style, (int)0x80000000 /*CW_USEDEFAULT*/, (int)0x80000000,
                               r.right - r.left, r.bottom - r.top, 0, 0, inst, 0);
    ShowWindow(w, 1);
    return w;
}

// ---------------------------------------------------------------- entry

static void say(const char *s) { DWORD n; HANDLE out = GetStdHandle((DWORD)-11); if (out && out != (HANDLE)-1) WriteFile(out, s, slen(s), &n, 0); }
static const char *nextArg(const char *c, char *out, unsigned cap) {
    while (*c == ' ' || *c == '\t') c++;
    unsigned n = 0;
    if (*c == '"') { c++; while (*c && *c != '"') { if (n + 1 < cap) out[n++] = *c; c++; } if (*c) c++; }
    else while (*c && *c != ' ' && *c != '\t') { if (n + 1 < cap) out[n++] = *c; c++; }
    out[n] = 0;
    return c;
}

void start(void) {
    SetProcessDPIAware();
    char arg[PATHLEN], val[PATHLEN];
    const char *c = nextArg(GetCommandLineA(), arg, sizeof(arg)); // program name
    c = nextArg(c, arg, sizeof(arg)); nextArg(c, val, sizeof(val));
    if (arg[0] == '/' || arg[0] == '-') {
        const char *cmd = arg + 1; int code = 0;
        if (sameText(cmd, "find")) { if (findGame(gameDir)) { say(gameDir); say("\r\n"); } else { say("not found\r\n"); code = 1; } }
        else {
            if (!val[0] && !findGame(val)) { say("Game not found; pass the Win64 folder.\r\n"); ExitProcess(1); }
            if (!isGameDir(val)) { say("Not the game's Win64 folder: "); say(val); say("\r\n"); ExitProcess(1); }
            if (sameText(cmd, "install")) { code = install(val, 0); say(code ? errorText[code] : "Installed."); say("\r\n"); }
            else if (sameText(cmd, "uninstall")) { code = uninstall(val, 0); say(code ? errorText[code] : "Uninstalled."); say("\r\n"); }
            else if (sameText(cmd, "recordon") || sameText(cmd, "recordoff")) { code = setRecording(val, sameText(cmd, "recordon")); say(code ? "Couldn't write the flag file." : "OK."); say("\r\n"); }
            else if (sameText(cmd, "report")) { char outp[PATHLEN]; code = writeReport(val, outp); say(code ? "Couldn't write the report." : outp); say("\r\n"); }
            else if (sameText(cmd, "off") || sameText(cmd, "on")) {
                int on = sameText(cmd, "on");
                code = installState(val) == NOT_INSTALLED ? 1 : turnOn(val, on);
                say(code ? "Couldn't switch it (not installed, or the file is in use)." : on ? "Turned on." : "Turned off."); say("\r\n");
            }
            else if (sameText(cmd, "serve")) {
                scpy(gameDir, sizeof(gameDir), val);
                if (!startServer()) { say("Couldn't start the server.\r\n"); ExitProcess(1); }
                char url[120]; editorUrl(url); say(url); say("\r\n");
                for (;;) Sleep(60000);
            } else if (sameText(cmd, "default") || sameText(cmd, "recommended") || sameText(cmd, "own")) {
                code = useLayout(val, sameText(cmd, "default") ? 0 : sameText(cmd, "recommended") ? 1 : 2);
                char active[PATHLEN]; activeSettings(val, active);
                say(code ? "Couldn't switch the layout." : "Key layout: "); if (!code) say(baseName(active)); say("\r\n");
            } else if (sameText(cmd, "status")) {
                const char *names[] = {"not installed", "installed, up to date", "installed, older version", "a different xinput1_4.dll is there", "turned off"};
                code = installState(val); say(names[code]);
                if (code == INSTALLED_LATEST || code == INSTALLED_OLDER || code == TURNED_OFF) { char active[PATHLEN]; activeSettings(val, active); say(", key layout: "); say(baseName(active)); }
                say("\r\n");
            } else { say("Unknown option.\r\n"); code = 1; }
        }
        ExitProcess(code);
    }
    findGame(gameDir);
    HANDLE w = createMain();
    MSG m;
    while (GetMessageA(&m, 0, 0, 0) > 0) if (!IsDialogMessageA(w, &m)) { TranslateMessage(&m); DispatchMessageA(&m); }
    ExitProcess(0);
}
