// Windows installer for the Minecraft Dungeons II keyboard controller mod.
//
// One exe with the mod inside (build/payload.h, generated by build.sh). It finds
// the game through Steam's library folders, copies xinput1_4.dll, wasd-mod.ini
// and the offline key layout editor into Dungeons\Binaries\Win64, and can
// uninstall, open the editor, load a layout the editor saved, or open the
// settings file. Windows loads xinput1_4.dll from the game folder first, so no
// registry change is needed (that is only for Wine; see install.command).
//
// Command line (also used by the tests under Wine):
//   /find                 print the game folder it finds
//   /status  "<folder>"   print what is installed there
//   /install "<folder>"   install without the window
//   /uninstall "<folder>" uninstall without the window (keeps wasd-mod.txt)
typedef unsigned char BYTE;
typedef unsigned short WORD;
typedef unsigned long DWORD;
typedef long LONG;
typedef unsigned int UINT;
typedef int BOOL;
typedef void *HANDLE;
typedef long long LRESULT;
typedef unsigned long long WPARAM;
typedef long long LPARAM;
typedef unsigned long long U64;
#define IMP __declspec(dllimport)

// kernel32
IMP HANDLE CreateFileA(const char *, DWORD, DWORD, void *, DWORD, DWORD, HANDLE);
IMP BOOL ReadFile(HANDLE, void *, DWORD, DWORD *, void *);
IMP BOOL WriteFile(HANDLE, const void *, DWORD, DWORD *, void *);
IMP DWORD GetFileSize(HANDLE, DWORD *);
IMP BOOL CloseHandle(HANDLE);
IMP BOOL DeleteFileA(const char *);
IMP BOOL CopyFileA(const char *, const char *, BOOL);
IMP DWORD GetFileAttributesA(const char *);
typedef struct { DWORD attributes; DWORD created[2], accessed[2], written[2]; DWORD sizeHigh, sizeLow; } FILEINFO;
IMP BOOL GetFileAttributesExA(const char *, int, FILEINFO *);
IMP BOOL SetFileTime(HANDLE, const void *, const void *, const void *);
IMP void GetSystemTimeAsFileTime(DWORD *);
IMP HANDLE GetProcessHeap(void);
IMP void *HeapAlloc(HANDLE, DWORD, U64);
IMP BOOL HeapFree(HANDLE, DWORD, void *);
IMP const char *GetCommandLineA(void);
IMP HANDLE GetStdHandle(DWORD);
IMP void ExitProcess(UINT);
IMP HANDLE GetModuleHandleA(const char *);
IMP DWORD GetEnvironmentVariableA(const char *, char *, DWORD);
IMP HANDLE CreateToolhelp32Snapshot(DWORD, DWORD);
typedef struct { DWORD size, usage, pid; U64 heap; DWORD module, threads, parent; LONG priority; DWORD flags; char exe[260]; } PROCESSENTRY;
IMP BOOL Process32First(HANDLE, PROCESSENTRY *);
IMP BOOL Process32Next(HANDLE, PROCESSENTRY *);
// advapi32
IMP LONG RegOpenKeyExA(HANDLE, const char *, DWORD, DWORD, HANDLE *);
IMP LONG RegQueryValueExA(HANDLE, const char *, DWORD *, DWORD *, BYTE *, DWORD *);
IMP LONG RegCloseKey(HANDLE);
// user32
typedef LRESULT (*WNDPROC)(HANDLE, UINT, WPARAM, LPARAM);
typedef struct { UINT style; WNDPROC proc; int clsExtra, wndExtra; HANDLE instance, icon, cursor, background; const char *menu, *className; } WNDCLASSA;
typedef struct { HANDLE hwnd; UINT message; WPARAM wParam; LPARAM lParam; DWORD time; LONG x, y; } MSG;
typedef struct { LONG left, top, right, bottom; } RECT;
IMP WORD RegisterClassA(const WNDCLASSA *);
IMP HANDLE CreateWindowExA(DWORD, const char *, const char *, DWORD, int, int, int, int, HANDLE, HANDLE, HANDLE, void *);
IMP LRESULT DefWindowProcA(HANDLE, UINT, WPARAM, LPARAM);
IMP BOOL GetMessageA(MSG *, HANDLE, UINT, UINT);
IMP BOOL TranslateMessage(const MSG *);
IMP LRESULT DispatchMessageA(const MSG *);
IMP BOOL IsDialogMessageA(HANDLE, MSG *);
IMP void PostQuitMessage(int);
IMP LRESULT SendMessageA(HANDLE, UINT, WPARAM, LPARAM);
IMP BOOL SetWindowTextA(HANDLE, const char *);
IMP int MessageBoxA(HANDLE, const char *, const char *, UINT);
IMP BOOL EnableWindow(HANDLE, BOOL);
IMP BOOL ShowWindow(HANDLE, int);
IMP HANDLE LoadCursorA(HANDLE, const char *);
IMP HANDLE LoadIconA(HANDLE, const char *);
IMP HANDLE GetDC(HANDLE);
IMP int ReleaseDC(HANDLE, HANDLE);
IMP BOOL AdjustWindowRect(RECT *, DWORD, BOOL);
IMP BOOL SetProcessDPIAware(void);
// gdi32
IMP HANDLE CreateFontA(int, int, int, int, int, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, const char *);
IMP int GetDeviceCaps(HANDLE, int);
IMP int SetBkMode(HANDLE, int);
IMP HANDLE GetSysColorBrush(int);
// shell32 / comdlg32
IMP HANDLE ShellExecuteA(HANDLE, const char *, const char *, const char *, const char *, int);
typedef struct {
    DWORD size; HANDLE owner, instance; const char *filter; char *customFilter; DWORD maxCustomFilter, filterIndex;
    char *file; DWORD maxFile; char *fileTitle; DWORD maxFileTitle; const char *initialDir, *title; DWORD flags;
    WORD fileOffset, fileExtension; const char *defExt; LPARAM custData; void *hook; const char *templateName;
    void *reserved1; DWORD reserved2, flagsEx;
} OPENFILENAMEA;
IMP BOOL GetOpenFileNameA(OPENFILENAMEA *);

void *memset(void *p, int v, U64 n) { volatile BYTE *c = p; while (n--) *c++ = (BYTE)v; return p; }
void *memcpy(void *d, const void *s, U64 n) { volatile BYTE *o = d; const BYTE *i = s; while (n--) *o++ = *i++; return d; }
int _fltused = 0;

#include "build/payload.h" // payloadDll, payloadIni, payloadEditor (+ ...Size)

// ---------------------------------------------------------------- strings

#define PATHLEN 600
static unsigned slen(const char *s) { unsigned n = 0; while (s[n]) n++; return n; }
static void scpy(char *d, unsigned cap, const char *s) { unsigned i = 0; while (s[i] && i + 1 < cap) { d[i] = s[i]; i++; } d[i] = 0; }
static void cat(char *d, unsigned cap, const char *s) { unsigned n = slen(d); if (n < cap) scpy(d + n, cap - n, s); }
static char low(char c) { return c >= 'A' && c <= 'Z' ? c + 32 : c; }
static int sameText(const char *a, const char *b) { while (*a && low(*a) == low(*b)) a++, b++; return !*a && !*b; }
static int contains(const char *hay, unsigned n, const char *needle) {
    unsigned m = slen(needle);
    for (unsigned i = 0; i + m <= n; i++) { unsigned j = 0; while (j < m && hay[i + j] == needle[j]) j++; if (j == m) return 1; }
    return 0;
}
static void join(char *out, const char *dir, const char *name) { scpy(out, PATHLEN, dir); cat(out, PATHLEN, "\\"); cat(out, PATHLEN, name); }

// ---------------------------------------------------------------- files

static int exists(const char *p) { return GetFileAttributesA(p) != 0xFFFFFFFF; }
static char *readAll(const char *p, DWORD *n) {
    HANDLE f = CreateFileA(p, 0x80000000 /*GENERIC_READ*/, 1 | 2 /*share read/write*/, 0, 3 /*OPEN_EXISTING*/, 0x80, 0);
    if (f == (HANDLE)-1) return 0;
    DWORD size = GetFileSize(f, 0), got = 0;
    char *b = HeapAlloc(GetProcessHeap(), 0, (U64)size + 1);
    if (b && (!ReadFile(f, b, size, &got, 0) || got != size)) { HeapFree(GetProcessHeap(), 0, b); b = 0; }
    CloseHandle(f);
    if (b) { b[size] = 0; *n = size; }
    return b;
}
static int writeAll(const char *p, const void *d, DWORD n) {
    HANDLE f = CreateFileA(p, 0x40000000 /*GENERIC_WRITE*/, 0, 0, 2 /*CREATE_ALWAYS*/, 0x80, 0);
    if (f == (HANDLE)-1) return 0;
    DWORD put = 0; BOOL ok = WriteFile(f, d, n, &put, 0) && put == n;
    CloseHandle(f);
    return ok;
}
static int sameAs(const char *p, const BYTE *d, DWORD n) {
    DWORD got; char *b = readAll(p, &got); if (!b) return 0;
    int same = got == n; for (DWORD i = 0; same && i < n; i++) if ((BYTE)b[i] != d[i]) same = 0;
    HeapFree(GetProcessHeap(), 0, b);
    return same;
}
static int isOurDll(const char *p) {
    DWORD n; char *b = readAll(p, &n); if (!b) return 0;
    int ours = contains(b, n, "Controller mod loaded") || contains(b, n, "WASD mod loaded");
    HeapFree(GetProcessHeap(), 0, b);
    return ours;
}
// Marks a file as just changed: the mod reads whichever of wasd-mod.ini and
// wasd-mod.txt is newer, so a saved layout stays in charge after an update.
static void touch(const char *p) {
    HANDLE f = CreateFileA(p, 0x100 /*FILE_WRITE_ATTRIBUTES*/, 1 | 2, 0, 3, 0x80, 0);
    if (f == (HANDLE)-1) return;
    DWORD now[2]; GetSystemTimeAsFileTime(now); SetFileTime(f, 0, 0, now);
    CloseHandle(f);
}
static int newer(const char *a, const char *b) { // a changed after b
    FILEINFO x, y;
    if (!GetFileAttributesExA(a, 0, &x)) return 0;
    if (!GetFileAttributesExA(b, 0, &y)) return 1;
    return x.written[1] > y.written[1] || (x.written[1] == y.written[1] && x.written[0] > y.written[0]);
}

static int gameRunning(void) {
    HANDLE s = CreateToolhelp32Snapshot(2 /*TH32CS_SNAPPROCESS*/, 0);
    if (s == (HANDLE)-1) return 0;
    PROCESSENTRY e; memset(&e, 0, sizeof(e)); e.size = sizeof(e);
    int found = 0;
    for (BOOL ok = Process32First(s, &e); ok && !found; ok = Process32Next(s, &e)) if (sameText(e.exe, "Dungeons-Win64-Shipping.exe")) found = 1;
    CloseHandle(s);
    return found;
}

// ---------------------------------------------------------------- finding the game

static const char *GAME_SUB = "steamapps\\common\\Minecraft Dungeons II\\Dungeons\\Binaries\\Win64";
static int isGameDir(const char *dir) { char p[PATHLEN]; join(p, dir, "Dungeons-Win64-Shipping.exe"); return exists(p); }

static int tryLibrary(const char *lib, char *out) {
    char dir[PATHLEN]; join(dir, lib, GAME_SUB);
    if (!isGameDir(dir)) return 0;
    scpy(out, PATHLEN, dir);
    return 1;
}
static int regString(HANDLE root, const char *key, const char *value, char *out, DWORD cap) {
    HANDLE k; if (RegOpenKeyExA(root, key, 0, 0x20019 /*KEY_READ*/, &k)) return 0;
    DWORD type = 0, size = cap - 1; LONG r = RegQueryValueExA(k, value, 0, &type, (BYTE *)out, &size);
    RegCloseKey(k);
    if (r || (type != 1 && type != 2)) return 0;
    out[size < cap ? size : cap - 1] = 0;
    for (char *c = out; *c; c++) if (*c == '/') *c = '\\';
    unsigned n = slen(out); while (n && out[n - 1] == '\\') out[--n] = 0;
    return out[0] != 0;
}
// Steam's library list: every "path" "D:\\SteamLibrary" entry in libraryfolders.vdf.
static int searchLibraries(const char *steam, char *out) {
    if (tryLibrary(steam, out)) return 1;
    char p[PATHLEN]; join(p, steam, "steamapps\\libraryfolders.vdf");
    DWORD n; char *b = readAll(p, &n); if (!b) return 0;
    int found = 0;
    for (DWORD i = 0; i + 6 < n && !found; i++) {
        if (b[i] != '"' || low(b[i + 1]) != 'p' || low(b[i + 2]) != 'a' || low(b[i + 3]) != 't' || low(b[i + 4]) != 'h' || b[i + 5] != '"') continue;
        DWORD j = i + 6; while (j < n && b[j] != '"' && b[j] != '\n') j++;
        if (j >= n || b[j] != '"') continue;
        char lib[PATHLEN]; unsigned k = 0; j++;
        while (j < n && b[j] != '"' && k + 1 < sizeof(lib)) {
            if (b[j] == '\\' && j + 1 < n && b[j + 1] == '\\') j++; // "D:\\SteamLibrary"
            lib[k++] = b[j] == '/' ? '\\' : b[j];
            j++;
        }
        lib[k] = 0;
        found = tryLibrary(lib, out);
    }
    HeapFree(GetProcessHeap(), 0, b);
    return found;
}
static int findGame(char *out) {
    char steam[PATHLEN];
    if (regString((HANDLE)0x80000001 /*HKCU*/, "Software\\Valve\\Steam", "SteamPath", steam, sizeof(steam)) && searchLibraries(steam, out)) return 1;
    if (regString((HANDLE)0x80000002 /*HKLM*/, "SOFTWARE\\WOW6432Node\\Valve\\Steam", "InstallPath", steam, sizeof(steam)) && searchLibraries(steam, out)) return 1;
    if (regString((HANDLE)0x80000002, "SOFTWARE\\Valve\\Steam", "InstallPath", steam, sizeof(steam)) && searchLibraries(steam, out)) return 1;
    const char *guesses[] = {"C:\\Program Files (x86)\\Steam", "C:\\Program Files\\Steam", "D:\\SteamLibrary", "D:\\Steam", "E:\\SteamLibrary"};
    for (unsigned i = 0; i < sizeof(guesses) / sizeof(*guesses); i++) if (tryLibrary(guesses[i], out)) return 1;
    return 0;
}
// A file the player picked: the game's exe in Win64, or Dungeons.exe at the top.
static int dirFromPick(const char *file, char *out) {
    scpy(out, PATHLEN, file);
    unsigned n = slen(out); while (n && out[n - 1] != '\\' && out[n - 1] != '/') n--;
    if (n) n--;
    out[n] = 0;
    if (isGameDir(out)) return 1;
    cat(out, PATHLEN, "\\Dungeons\\Binaries\\Win64");
    return isGameDir(out);
}

// ---------------------------------------------------------------- install / uninstall

enum { OK, ERR_RUNNING, ERR_OTHER_DLL, ERR_WRITE };
static const char *errorText[] = {
    "",
    "Minecraft Dungeons II is running. Close it, then try again.",
    "The game folder already has a different xinput1_4.dll (another mod?).",
    "Couldn't write to the game folder. Try running this installer as administrator.",
};

static int install(const char *dir, int replaceOther) {
    if (gameRunning()) return ERR_RUNNING;
    char dll[PATHLEN], ini[PATHLEN], txt[PATHLEN], editor[PATHLEN], p[PATHLEN];
    join(dll, dir, "xinput1_4.dll"); join(ini, dir, "wasd-mod.ini"); join(txt, dir, "wasd-mod.txt"); join(editor, dir, "Key Layout Editor.html");
    if (exists(dll) && !isOurDll(dll)) {
        if (!replaceOther) return ERR_OTHER_DLL;
        join(p, dir, "xinput1_4.dll.other");
        if (!CopyFileA(dll, p, 0)) return ERR_WRITE;
    }
    if (!writeAll(dll, payloadDll, sizeof(payloadDll))) return ERR_WRITE;
    if (exists(ini) && !sameAs(ini, payloadIni, sizeof(payloadIni))) { join(p, dir, "wasd-mod.ini.bak"); CopyFileA(ini, p, 0); }
    if (!writeAll(ini, payloadIni, sizeof(payloadIni))) return ERR_WRITE;
    writeAll(editor, payloadEditor, sizeof(payloadEditor));
    if (exists(txt)) touch(txt);
    return OK;
}

static int uninstall(const char *dir, int removeLayout) {
    if (gameRunning()) return ERR_RUNNING;
    char p[PATHLEN];
    join(p, dir, "xinput1_4.dll"); if (exists(p) && isOurDll(p) && !DeleteFileA(p)) return ERR_WRITE;
    const char *files[] = {"wasd-mod.ini", "wasd-mod.ini.bak", "wasd-mod.log", "Key Layout Editor.html"};
    for (unsigned i = 0; i < 4; i++) { join(p, dir, files[i]); DeleteFileA(p); }
    if (removeLayout) { join(p, dir, "wasd-mod.txt"); DeleteFileA(p); }
    return OK;
}

enum { NOT_INSTALLED, INSTALLED_LATEST, INSTALLED_OLDER, OTHER_DLL };
static int installState(const char *dir) {
    char dll[PATHLEN]; join(dll, dir, "xinput1_4.dll");
    if (!exists(dll)) return NOT_INSTALLED;
    if (!isOurDll(dll)) return OTHER_DLL;
    return sameAs(dll, payloadDll, sizeof(payloadDll)) ? INSTALLED_LATEST : INSTALLED_OLDER;
}
// The settings file the mod uses: wasd-mod.txt (a saved layout) when it's the newer one.
static void activeSettings(const char *dir, char *out) {
    char ini[PATHLEN], txt[PATHLEN]; join(ini, dir, "wasd-mod.ini"); join(txt, dir, "wasd-mod.txt");
    scpy(out, PATHLEN, exists(txt) && newer(txt, ini) ? txt : ini);
}

// ---------------------------------------------------------------- window

enum { ID_PATH = 10, ID_BROWSE, ID_INSTALL, ID_UNINSTALL, ID_EDITOR, ID_LOAD, ID_SETTINGS, ID_STATUS };
static HANDLE mainWnd, fontNormal, fontTitle, fontSmall, statusWnd, pathWnd, installBtn, uninstallBtn, editorBtn, loadBtn, settingsBtn;
static char gameDir[PATHLEN];
static int dpi = 96;
static int S(int v) { return v * dpi / 96; }
static const char *TITLE = "Minecraft Dungeons II Controller Mod";

static void refresh(void) {
    char text[900] = "";
    int have = gameDir[0] != 0, state = have ? installState(gameDir) : NOT_INSTALLED;
    SetWindowTextA(pathWnd, have ? gameDir : "(not found)");
    unsigned end = slen(have ? gameDir : "(not found)");
    SendMessageA(pathWnd, 0xB1 /*EM_SETSEL*/, end, end); // show the end of a long path
    if (!have) scpy(text, sizeof(text), "Game not found. Click Browse and pick Dungeons-Win64-Shipping.exe (in Dungeons\\Binaries\\Win64) or Dungeons.exe.");
    else if (state == INSTALLED_LATEST) scpy(text, sizeof(text), "Installed and up to date. Start (or restart) the game to use it.");
    else if (state == INSTALLED_OLDER) scpy(text, sizeof(text), "An older version is installed. Click Update.");
    else if (state == OTHER_DLL) scpy(text, sizeof(text), "The game folder has a different xinput1_4.dll (another mod?). Install replaces it and keeps a copy as xinput1_4.dll.other.");
    else scpy(text, sizeof(text), "Not installed yet.");
    if (have && state != NOT_INSTALLED && state != OTHER_DLL) {
        char txt[PATHLEN]; join(txt, gameDir, "wasd-mod.txt");
        if (exists(txt)) cat(text, sizeof(text), " Using your saved key layout (wasd-mod.txt).");
    }
    SetWindowTextA(statusWnd, text);
    SetWindowTextA(installBtn, state == INSTALLED_OLDER ? "Update" : state == INSTALLED_LATEST ? "Reinstall" : "Install");
    EnableWindow(installBtn, have);
    int installed = have && (state == INSTALLED_LATEST || state == INSTALLED_OLDER);
    EnableWindow(uninstallBtn, installed);
    EnableWindow(editorBtn, have);
    EnableWindow(loadBtn, installed);
    EnableWindow(settingsBtn, installed);
}

static int pickFile(const char *title, const char *filter, const char *initialDir, char *out) {
    OPENFILENAMEA o; memset(&o, 0, sizeof(o));
    out[0] = 0;
    o.size = sizeof(o); o.owner = mainWnd; o.filter = filter; o.filterIndex = 1; o.file = out; o.maxFile = PATHLEN;
    o.initialDir = initialDir; o.title = title; o.flags = 0x1000 | 0x800 | 0x4 | 0x8; // must exist, hide read-only, keep directory
    return GetOpenFileNameA(&o);
}

static void onCommand(int id) {
    char p[PATHLEN];
    if (id == ID_BROWSE) {
        if (!pickFile("Find Minecraft Dungeons II", "Minecraft Dungeons II (Dungeons*.exe)\0Dungeons*.exe\0All files\0*.*\0", 0, p)) return;
        char dir[PATHLEN];
        if (dirFromPick(p, dir)) scpy(gameDir, sizeof(gameDir), dir);
        else MessageBoxA(mainWnd, "That isn't the Minecraft Dungeons II folder. Pick Dungeons-Win64-Shipping.exe (in Dungeons\\Binaries\\Win64) or Dungeons.exe.", TITLE, 0x30);
    } else if (id == ID_INSTALL) {
        int r = install(gameDir, 0);
        if (r == ERR_OTHER_DLL && MessageBoxA(mainWnd, "The game folder already has a different xinput1_4.dll (probably another mod). Replace it? A copy is kept as xinput1_4.dll.other.", TITLE, 0x4 | 0x30) == 6) r = install(gameDir, 1);
        if (r == OK) MessageBoxA(mainWnd, "Installed. Start (or restart) Minecraft Dungeons II.\n\nIn game: WASD moves, F9 shows the key list, and the backtick key (`) turns the mod off and on.", TITLE, 0x40);
        else if (r != ERR_OTHER_DLL) MessageBoxA(mainWnd, errorText[r], TITLE, 0x30);
    } else if (id == ID_UNINSTALL) {
        join(p, gameDir, "wasd-mod.txt");
        int removeLayout = exists(p) && MessageBoxA(mainWnd, "Also delete your saved key layout (wasd-mod.txt)?", TITLE, 0x4 | 0x20) == 6;
        int r = uninstall(gameDir, removeLayout);
        MessageBoxA(mainWnd, r == OK ? "Uninstalled. The game is back to how it was." : errorText[r], TITLE, r == OK ? 0x40 : 0x30);
    } else if (id == ID_EDITOR) {
        join(p, gameDir, "Key Layout Editor.html");
        if (!sameAs(p, payloadEditor, sizeof(payloadEditor)) && !writeAll(p, payloadEditor, sizeof(payloadEditor))) { MessageBoxA(mainWnd, errorText[ERR_WRITE], TITLE, 0x30); return; }
        ShellExecuteA(mainWnd, "open", p, 0, 0, 1);
        SetWindowTextA(statusWnd, "The key layout editor opened in your browser. When you save there it downloads wasd-mod.ini; then click \"Load layout file\" here.");
        return;
    } else if (id == ID_LOAD) {
        char downloads[PATHLEN] = "";
        if (GetEnvironmentVariableA("USERPROFILE", downloads, 300)) cat(downloads, sizeof(downloads), "\\Downloads");
        if (!pickFile("Load a key layout", "Key layout (*.ini;*.txt)\0*.ini;*.txt\0All files\0*.*\0", downloads[0] ? downloads : 0, p)) return;
        DWORD n; char *b = readAll(p, &n);
        int valid = b && (contains(b, n, "[Buttons]") || contains(b, n, "[Move]"));
        char dest[PATHLEN]; join(dest, gameDir, "wasd-mod.txt");
        if (!valid) MessageBoxA(mainWnd, "That file isn't a key layout (it has no [Buttons] or [Move] section).", TITLE, 0x30);
        else if (!writeAll(dest, b, n)) MessageBoxA(mainWnd, errorText[ERR_WRITE], TITLE, 0x30);
        else MessageBoxA(mainWnd, "Key layout loaded. Restart the game to use it.", TITLE, 0x40);
        if (b) HeapFree(GetProcessHeap(), 0, b);
    } else if (id == ID_SETTINGS) {
        activeSettings(gameDir, p);
        char quoted[PATHLEN + 2] = "\""; cat(quoted, sizeof(quoted), p); cat(quoted, sizeof(quoted), "\"");
        ShellExecuteA(mainWnd, "open", "notepad.exe", quoted, 0, 1);
        return;
    } else return;
    refresh();
}

static HANDLE control(const char *cls, const char *text, DWORD style, int x, int y, int w, int h, int id, HANDLE font) {
    HANDLE c = CreateWindowExA(cls[0] == 'E' ? 0x200 /*WS_EX_CLIENTEDGE*/ : 0, cls, text, 0x50000000 /*WS_CHILD|WS_VISIBLE*/ | style,
                               S(x), S(y), S(w), S(h), mainWnd, (HANDLE)(U64)id, GetModuleHandleA(0), 0);
    SendMessageA(c, 0x30 /*WM_SETFONT*/, (WPARAM)font, 1);
    return c;
}

static LRESULT wndProc(HANDLE w, UINT msg, WPARAM wp, LPARAM lp) {
    if (msg == 0x01) { // WM_CREATE
        mainWnd = w;
        control("STATIC", "Keyboard Controller Mod", 0, 20, 16, 480, 30, 0, fontTitle);
        control("STATIC", "Play Minecraft Dungeons II with WASD, mouse and keys, as a controller.", 0, 20, 48, 480, 20, 0, fontSmall);
        control("STATIC", "Game folder", 0, 20, 84, 200, 20, 0, fontNormal);
        pathWnd = control("EDIT", "", 0x80 /*ES_AUTOHSCROLL*/ | 0x800 /*ES_READONLY*/, 20, 106, 386, 26, ID_PATH, fontNormal);
        control("BUTTON", "Browse...", 0x10000 /*WS_TABSTOP*/, 414, 105, 86, 28, ID_BROWSE, fontNormal);
        statusWnd = control("STATIC", "", 0, 20, 144, 480, 42, ID_STATUS, fontNormal);
        installBtn = control("BUTTON", "Install", 0x10000 | 0x1 /*BS_DEFPUSHBUTTON*/, 20, 194, 150, 34, ID_INSTALL, fontNormal);
        uninstallBtn = control("BUTTON", "Uninstall", 0x10000, 178, 194, 110, 34, ID_UNINSTALL, fontNormal);
        control("STATIC", "Key layout", 0, 20, 246, 200, 20, 0, fontNormal);
        editorBtn = control("BUTTON", "Edit key layout...", 0x10000, 20, 268, 156, 30, ID_EDITOR, fontNormal);
        loadBtn = control("BUTTON", "Load layout file...", 0x10000, 184, 268, 156, 30, ID_LOAD, fontNormal);
        settingsBtn = control("BUTTON", "Open settings file", 0x10000, 348, 268, 152, 30, ID_SETTINGS, fontNormal);
        control("STATIC", "Restart the game after any change. In game: F9 shows the key list; backtick (`) turns the mod off and on.", 0, 20, 312, 480, 36, 0, fontSmall);
        refresh();
        return 0;
    }
    if (msg == 0x111 /*WM_COMMAND*/ && (wp >> 16) == 0 /*BN_CLICKED*/) { onCommand((int)(wp & 0xFFFF)); return 0; }
    if (msg == 0x138 /*WM_CTLCOLORSTATIC*/ && (HANDLE)lp != pathWnd) { // labels on the window background
        SetBkMode((HANDLE)wp, 1 /*TRANSPARENT*/);
        return (LRESULT)GetSysColorBrush(15 /*COLOR_BTNFACE*/);
    }
    if (msg == 0x02) { PostQuitMessage(0); return 0; } // WM_DESTROY
    return DefWindowProcA(w, msg, wp, lp);
}

static HANDLE createMain(void) {
    HANDLE inst = GetModuleHandleA(0);
    HANDLE dc = GetDC(0); dpi = GetDeviceCaps(dc, 88 /*LOGPIXELSX*/); ReleaseDC(0, dc);
    if (dpi < 96) dpi = 96;
    fontNormal = CreateFontA(-S(15), 0, 0, 0, 400, 0, 0, 0, 1, 0, 0, 5 /*CLEARTYPE*/, 0, "Segoe UI");
    fontSmall = CreateFontA(-S(13), 0, 0, 0, 400, 0, 0, 0, 1, 0, 0, 5, 0, "Segoe UI");
    fontTitle = CreateFontA(-S(22), 0, 0, 0, 600, 0, 0, 0, 1, 0, 0, 5, 0, "Segoe UI");
    WNDCLASSA wc; memset(&wc, 0, sizeof(wc));
    wc.proc = wndProc; wc.instance = inst; wc.className = "DungeonsControllerModSetup";
    wc.icon = LoadIconA(inst, (const char *)1); wc.cursor = LoadCursorA(0, (const char *)32512 /*IDC_ARROW*/);
    wc.background = (HANDLE)(15 + 1); // COLOR_BTNFACE
    RegisterClassA(&wc);
    DWORD style = 0x00CA0000; // caption, system menu, minimize box
    RECT r = {0, 0, S(520), S(356)}; AdjustWindowRect(&r, style, 0);
    HANDLE w = CreateWindowExA(0, wc.className, TITLE, style, (int)0x80000000 /*CW_USEDEFAULT*/, (int)0x80000000,
                               r.right - r.left, r.bottom - r.top, 0, 0, inst, 0);
    ShowWindow(w, 1);
    return w;
}

// ---------------------------------------------------------------- entry

static void say(const char *s) { DWORD n; HANDLE out = GetStdHandle((DWORD)-11); if (out && out != (HANDLE)-1) WriteFile(out, s, slen(s), &n, 0); }
static const char *nextArg(const char *c, char *out, unsigned cap) {
    while (*c == ' ' || *c == '\t') c++;
    unsigned n = 0;
    if (*c == '"') { c++; while (*c && *c != '"') { if (n + 1 < cap) out[n++] = *c; c++; } if (*c) c++; }
    else while (*c && *c != ' ' && *c != '\t') { if (n + 1 < cap) out[n++] = *c; c++; }
    out[n] = 0;
    return c;
}

void start(void) {
    SetProcessDPIAware();
    char arg[PATHLEN], val[PATHLEN];
    const char *c = nextArg(GetCommandLineA(), arg, sizeof(arg)); // program name
    c = nextArg(c, arg, sizeof(arg)); nextArg(c, val, sizeof(val));
    if (arg[0] == '/' || arg[0] == '-') {
        const char *cmd = arg + 1; int code = 0;
        if (sameText(cmd, "find")) { if (findGame(gameDir)) { say(gameDir); say("\r\n"); } else { say("not found\r\n"); code = 1; } }
        else {
            if (!val[0] && !findGame(val)) { say("Game not found; pass the Win64 folder.\r\n"); ExitProcess(1); }
            if (!isGameDir(val)) { say("Not the game's Win64 folder: "); say(val); say("\r\n"); ExitProcess(1); }
            if (sameText(cmd, "install")) { code = install(val, 0); say(code ? errorText[code] : "Installed."); say("\r\n"); }
            else if (sameText(cmd, "uninstall")) { code = uninstall(val, 0); say(code ? errorText[code] : "Uninstalled."); say("\r\n"); }
            else if (sameText(cmd, "status")) {
                const char *names[] = {"not installed", "installed, up to date", "installed, older version", "a different xinput1_4.dll is there"};
                code = installState(val); say(names[code]); say("\r\n");
            } else { say("Unknown option.\r\n"); code = 1; }
        }
        ExitProcess(code);
    }
    findGame(gameDir);
    HANDLE w = createMain();
    MSG m;
    while (GetMessageA(&m, 0, 0, 0) > 0) if (!IsDialogMessageA(w, &m)) { TranslateMessage(&m); DispatchMessageA(&m); }
    ExitProcess(0);
}
