#!/usr/bin/env python3
"""Generates the Windows installer's inputs (run by build.sh):

build/payload.h     the mod DLL, default settings and key layout editor as C arrays
build/installer.res icon + manifest, in the .res format lld-link links directly
"""
import struct, zlib

def c_array(name, data):
    rows = [", ".join("0x%02x" % b for b in data[i:i + 20]) for i in range(0, len(data), 20)]
    return "static const unsigned char %s[] = {\n%s\n};\n" % (name, ",\n".join(rows))

with open("build/payload.h", "w") as f:
    f.write("// Generated by pack_windows.py; do not edit.\n")
    for name, path in [("payloadDll", "build/xinput1_4.dll"), ("payloadIni", "wasdmod.ini"), ("payloadEditor", "Keybinder.html")]:
        f.write(c_array(name, open(path, "rb").read()))

# ---- icon: a 16x16 pixel-art gamepad, scaled up without smoothing
ART = [
    "................",
    "................",
    "................",
    "..oooooooooooo..",
    ".ohhhhhhhhhhhho.",
    "obbbwbbbbbbybbbo",
    "obbwwwbbbbubrbbo",
    "obbbwbbbbbbgbbbo",
    "obbbbbbbbbbbbbbo",
    "obbbbboooobbbbbo",
    ".obbbo....obbbo.",
    "..ooo......ooo..",
    "................",
    "................",
    "................",
    "................",
]
COLORS = {".": (0, 0, 0, 0), "o": (27, 29, 34, 255), "b": (74, 79, 89, 255), "h": (107, 113, 125, 255),
          "w": (238, 240, 242, 255), "g": (63, 191, 95, 255), "r": (224, 70, 60, 255),
          "y": (242, 194, 48, 255), "u": (61, 139, 240, 255)}
assert all(len(r) == 16 for r in ART) and len(ART) == 16

def png(size):
    scale = size // 16
    raw = b""
    for y in range(size):
        row = ART[y // scale]
        raw += b"\0" + b"".join(bytes(COLORS[row[x // scale]]) for x in range(size))
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))

MANIFEST = b"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity type="win32" name="DungeonsII.ControllerMod.Setup" version="1.0.0.0" processorArchitecture="amd64"/>
  <description>Minecraft Dungeons II Controller Mod</description>
  <dependency><dependentAssembly>
    <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/>
  </dependentAssembly></dependency>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"><security><requestedPrivileges>
    <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
  </requestedPrivileges></security></trustInfo>
  <application xmlns="urn:schemas-microsoft-com:asm.v3"><windowsSettings>
    <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
  </windowsSettings></application>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"><application>
    <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
  </application></compatibility>
</assembly>
"""

def resource(kind, ident, data, flags=0x1030, lang=0x0409):
    header = struct.pack("<II", len(data), 32) + struct.pack("<HHHH", 0xFFFF, kind, 0xFFFF, ident) \
        + struct.pack("<IHHII", 0, flags, lang, 0, 0)
    pad = b"\0" * (-len(data) % 4)
    return header + data + pad

sizes = [16, 32, 48, 256]
images = [png(s) for s in sizes]
res = resource(0, 0, b"", flags=0, lang=0)  # the empty entry every .res starts with
group = struct.pack("<HHH", 0, 1, len(sizes))
for i, (s, img) in enumerate(zip(sizes, images)):
    res += resource(3, i + 1, img)  # RT_ICON
    group += struct.pack("<BBBBHHIH", s % 256, s % 256, 0, 0, 1, 32, len(img), i + 1)
res += resource(14, 1, group)       # RT_GROUP_ICON, id 1 (LoadIcon(inst, 1))
res += resource(24, 1, MANIFEST, flags=0x0030)  # RT_MANIFEST
open("build/installer.res", "wb").write(res)
